USE CARRERAS_1;

DELIMITER $$
DROP PROCEDURE IF EXISTS PR_ALTA_CARRERA$$
CREATE PROCEDURE PR_ALTA_CARRERA( OUT PS_ID_CARRERA INT)
BEGIN
    -- rESETEAMOS LA VARIABLE DE SALIDA A NULO
    SET PS_ID_CARRERA= NULL;

    -- INSERTAMOS UN REGISTRO CON TODOS LO VALORES A NULOS
    INSERT INTO RESULTADO 
     VALUES (DEFAULT,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

    -- OBTENER LA VARIABLE CON UN PARAMETRO DE SALIDA
    -- SET PS_ID_CARRERA= LAST_INSERT_ID(); ( OTRA MANERA DE HACERLO)
    SELECT
    LAST_INSERT_ID()
    INTO PS_ID_CARRERA;
    
END $$

DELIMITER ;


DELIMITER $$
DROP PROCEDURE IF EXISTS PR_RESULTADO$$
CREATE PROCEDURE PR_RESULTADO(
                              IN PE_ID_CARRERA INT,
							  IN PE_ID_PRIMERO INT,
						      IN PE_ID_SEGUNDO INT,
							  IN PE_ID_TERCERO INT,
							  IN PE_ID_CUARTO INT,
							  IN PE_ID_QUINTO INT,
							  IN PE_ID_SEXTO INT,
							  IN PE_ID_SEPTIMO INT)
BEGIN

IF PE_ID_PRIMERO < 1 OR PE_ID_PRIMERO > 7 OR
       PE_ID_SEGUNDO < 1 OR PE_ID_SEGUNDO > 7 OR
       PE_ID_TERCERO < 1 OR PE_ID_TERCERO > 7 OR
       PE_ID_CUARTO < 1 OR PE_ID_CUARTO > 7 OR
       PE_ID_QUINTO < 1 OR PE_ID_QUINTO > 7 OR
       PE_ID_SEXTO < 1 OR PE_ID_SEXTO > 7 OR
       PE_ID_SEPTIMO < 1 OR PE_ID_SEPTIMO > 7 THEN
       SET @MENSAJE = CONCAT( 'LOS VALORES DE LOS PUESTOS Y DE LA ID:   ', PE_ID_CARRERA, 'DEBEN ESTAR DEBTRO DEL RANGO DEL 1 AL 7');
        SIGNAL SQLSTATE '45000'  SET MESSAGE_TEXT = @MENSAJE;
       
    
    END IF;

 SET @ID_CARRERA= NULL;
 SET @PUESTO1 = NULL;
 
 SELECT ID_CARRERA, PUESTO1
 FROM RESULTADO
 WHERE ID_CARRERA = PE_ID_CARRERA
 INTO @ID_CARRERA;
 
 IF @ID_CARRERA IS NULL THEN
 SET @MENSAJE = CONCAT( 'LA CARRERA CON ID', PE_ID_CARRRERA, 'NO EXISTE');
 SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT =@MENSAJE;
 ELSEIF @PUESTO1 IS NOT NULL THEN
 SET @MENSAJE = CONCAT( 'EL RESULTADO DE LA CARRERA CON ID', PE_ID_CARRRERA, 'YA ESTA CERRADA');
 SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT =@MENSAJE;
     -- Insertar los resultados en la tabla RESULTADO
 ELSE 
       UPDATE RESULTADO
    SET  PUESTO1 = PE_ID_PRIMERO,
         PUESTO2 = PE_ID_SEGUNDO,
         PUESTO3 = PE_ID_TERCERO ,
         PUESTO4 = PE_ID_CUARTO ,
         PUESTO5 = PE_ID_QUINTO,
         PUESTO6 = PE_ID_SEXTO,
         PUESTO7 = PE_ID_SEPTIMO 
         WHERE ID_CARRER = PE_ID_CARRERA;
 
 END IF;
 
 
    
   
END $$

DELIMITER ;

