CREATE VIEW RESUMEN_AEROPUERTO AS 
 SELECT DETALLES_VUELO.ID_DETALLES_VUELO AS 'CODIGO',
                ORIGEN.NOMBRE AS 'CUIDAD ORIGEN',
                O_PAISES.NOMBRE AS 'PAIS ORIGEN',
                DESTINO.NOMBRE AS 'CIUDAD DESTINO',
                D_PAISES.NOMBRE AS 'PAIS DESTINO',
                COMPANIA.NOMBRE AS 'COMPAÑIA',
                TIPO_VUELO.TIPO_VUELO AS 'TRAYECTO',
                DETALLES_VUELO.DURACION AS 'DURACION',
                DETALLES_VUELO.HORA AS 'HORA',
                DETALLES_VUELO.FECHA AS 'FECHA'
           FROM DETALLES_VUELO
				INNER JOIN TRAYECTO ON DETALLES_VUELO.ID_TRAYECTO = TRAYECTO.ID_TRAYECTO
                INNER JOIN AEROPUERTOS ORIGEN ON ORIGEN.ID_AEROPUERTO = TRAYECTO.ID_ORIGEN
                INNER JOIN AEROPUERTOS DESTINO ON DESTINO.ID_AEROPUERTO = TRAYECTO.ID_DESTINO
                INNER JOIN PAISES O_PAISES ON O_PAISES.ID_PAIS = ORIGEN.ID_PAIS
                INNER JOIN PAISES D_PAISES ON D_PAISES.ID_PAIS = DESTINO.ID_PAIS
                INNER JOIN COMPANIA ON DETALLES_VUELO.ID_COMPANIA = COMPANIA.ID_COMPANIA
                INNER JOIN TIPO_VUELO ON TIPO_VUELO.ID_TIPO = DETALLES_VUELO.ID_TIPO
                ORDER BY ID_DETALLES_VUELO;
