-- 1 -- Actualiza la fecha de los partidos de las jornadas 1 y 2 al 13 y 20 de agsoto 2023

  update partidos
         set fecha = '20230820'
         where jornada = 2;
  update partidos
        set fecha = '20230813'
        where jornada = 1;
        
  -- 2 -----Conta quien jugo el ATl.Madrid la jornada 2
  
SELECT EQUIPOS.NOMBRE
FROM EQUIPOS WHERE ID_EQUIPO IN( SELECT PARTIDOS.ID_LOCAL
								 FROM PARTIDOS
                                 INNER JOIN EQUIPOS ON PARTIDOS.ID_VISITANTE= EQUIPOS.ID_EQUIPO
                                 WHERE JORNADA = 2 AND EQUIPOS.NOMBRE = 'ATLETICO DE MADRID')
                   OR ID_EQUIPO IN  ( SELECT PARTIDOS.ID_LOCAL
								 FROM PARTIDOS
                                 INNER JOIN EQUIPOS ON PARTIDOS.ID_VISITANTE= EQUIPOS.ID_EQUIPO
                                 WHERE JORNADA = 2 AND EQUIPOS.NOMBRE = 'ATLETICO DE MADRID') ;
  
  -- 3--  PARTIDOS JUGADOS POR EL VILLARREAL
  
  SELECT P_JUGADOS, PUNTOS, NOMBRE
  FROM EQUIPOS
  WHERE NOMBRE = 'VILLARREAL';
  
  -- 4 QUINES GANADOR LA PRIMERA JORNADA DE LIGA
  
  SELECT EQUIPOS.NOMBRE, PL.RESULTADO, PV.RESULTADO
  FROM EQUIPOS INNER JOIN PARTIDOS PL ON PL.ID_LOCAL = EQUIPOS.ID_EQUIPO
               INNER JOIN PARTIDOS PV ON PV.ID_VISITANTE = EQUIPOS.ID_EQUIPO
  WHERE (PL.JORNADA AND PV.JORNADA) = 1 
        AND (PL.RESULTADO LIKE 'L' OR PL.RESULTADO LIKE 'V')
        AND (PV.RESULTADO LIKE 'L' OR PV.RESULTADO LIKE 'V') ;
        
   -- 5 QUE EQUIPOS TIENEN MAS DE 4 PUNTOS
   
   SELECT NOMBRE, PUNTOS
   FROM EQUIPOS
   WHERE PUNTOS > 4;
   
   -- 6 CUANTOS EQUIPOS TIENEN MAS DE 4 PUNTOS--
    SELECT COUNT(NOMBRE) AS 'NUMERO DE EQUIPOS'
   FROM EQUIPOS
   WHERE PUNTOS > 4;