DROP TABLE IF EXISTS TIPO_VUELO;
CREATE TABLE TIPO_VUELO(
ID_TIPO CHAR(1),
TIPO_VUELO CHAR(20),
PRIMARY KEY (ID_TIPO),
CONSTRAINT CHK_VALUE CHECK(ID_TIPO IN ('V', 'F'))
);

INSERT INTO TIPO_VUELO VALUES('V', 'Directo'),('F','Con escala');

-- -----------------------------Empezamos a desnormalizacion ------------------------

ALTER TABLE VIAJES
ADD ID_TIPO_VUELO CHAR(1)
CHECK(ID_TIPO_VUELO IN ('V', 'F'))
AFTER TIPO_VUELO;

UPDATE VIAJES
SET ID_TIPO_VUELO = 'V'
WHERE TIPO_VUELO = 'Directo';

UPDATE VIAJES
SET ID_TIPO_VUELO = 'F'
WHERE TIPO_VUELO = 'Con escala';

ALTER TABLE VIAJES
DROP TIPO_VUELO;

-- ---------------------------------- Ahora cogemos los trayectos----------------------------

DROP TABLE IF EXISTS TRAYECTO;
CREATE TABLE TRAYECTO (
	ID_TRAYECTO INT AUTO_INCREMENT,
    ID_ORIGEN INT UNSIGNED,
    ID_DESTINO INT UNSIGNED,
    PRIMARY KEY (ID_TRAYECTO),
    FOREIGN KEY (ID_ORIGEN) REFERENCES AEROPUERTOS(ID_AEROPUERTO),
    FOREIGN KEY (ID_DESTINO) REFERENCES AEROPUERTOS(ID_AEROPUERTO)
);

INSERT INTO TRAYECTO VALUES (DEFAULT, 1, 2);
INSERT INTO TRAYECTO VALUES (DEFAULT, 1, 3);
INSERT INTO TRAYECTO VALUES (DEFAULT, 1, 4);
INSERT INTO TRAYECTO VALUES (DEFAULT, 1, 5);
INSERT INTO TRAYECTO VALUES (DEFAULT, 1, 6);
INSERT INTO TRAYECTO VALUES (DEFAULT, 2, 1);
INSERT INTO TRAYECTO VALUES (DEFAULT, 2, 3);
INSERT INTO TRAYECTO VALUES (DEFAULT, 2, 4);
INSERT INTO TRAYECTO VALUES (DEFAULT, 2, 5);
INSERT INTO TRAYECTO VALUES (DEFAULT, 2, 6);
INSERT INTO TRAYECTO VALUES (DEFAULT, 3, 1);
INSERT INTO TRAYECTO VALUES (DEFAULT, 3, 2);
INSERT INTO TRAYECTO VALUES (DEFAULT, 3, 4);
INSERT INTO TRAYECTO VALUES (DEFAULT, 3, 5);
INSERT INTO TRAYECTO VALUES (DEFAULT, 3, 6);
INSERT INTO TRAYECTO VALUES (DEFAULT, 4, 1);
INSERT INTO TRAYECTO VALUES (DEFAULT, 4, 2);
INSERT INTO TRAYECTO VALUES (DEFAULT, 4, 3);
INSERT INTO TRAYECTO VALUES (DEFAULT, 4, 5);
INSERT INTO TRAYECTO VALUES (DEFAULT, 4, 6);
INSERT INTO TRAYECTO VALUES (DEFAULT, 5, 1);
INSERT INTO TRAYECTO VALUES (DEFAULT, 5, 2);
INSERT INTO TRAYECTO VALUES (DEFAULT, 5, 3);
INSERT INTO TRAYECTO VALUES (DEFAULT, 5, 4);
INSERT INTO TRAYECTO VALUES (DEFAULT, 5, 6);
INSERT INTO TRAYECTO VALUES (DEFAULT, 6, 1);
INSERT INTO TRAYECTO VALUES (DEFAULT, 6, 2);
INSERT INTO TRAYECTO VALUES (DEFAULT, 6, 3);
INSERT INTO TRAYECTO VALUES (DEFAULT, 6, 4);
INSERT INTO TRAYECTO VALUES (DEFAULT, 6, 5);

-- -------------------------------------Ahora cogemos la de compania ------------------------------

DROP TABLE IF EXISTS COMPANIA;
CREATE TABLE COMPANIA (
	ID_COMPANIA INT AUTO_INCREMENT,
    NOMBRE VARCHAR(40),
    PRIMARY KEY (ID_COMPANIA)
);

INSERT INTO COMPANIA VALUES(DEFAULT, 'Avianca');
INSERT INTO COMPANIA VALUES(DEFAULT, 'EasyJet');
INSERT INTO COMPANIA VALUES(DEFAULT, 'Air France');
INSERT INTO COMPANIA VALUES(DEFAULT, 'Air Italia');


-- -------------------------------------Ahora cogemos la de detalles_vuelo------------------------------
DROP TABLE IF EXISTS DETALLES_VUELO;
CREATE TABLE DETALLES_VUELO (
	ID_DETALLES_VUELO INT AUTO_INCREMENT,
    ID_TRAYECTO INT,
    ID_COMPANIA INT,
    ID_TIPO CHAR(1),
    DURACION TIME,
    FECHA DATE,
    HORA TIME,
    PRIMARY KEY (ID_DETALLES_VUELO),
    FOREIGN KEY (ID_TRAYECTO) REFERENCES TRAYECTO(ID_TRAYECTO),
    FOREIGN KEY (ID_COMPANIA) REFERENCES COMPANIA(ID_COMPANIA),
    FOREIGN KEY (ID_TIPO) REFERENCES TIPO_VUELO(ID_TIPO),
    CHECK (ID_TIPO IN ('V', 'F'))
);

 -- CALL RELLENAR_TRAYECTOS();

