set search_path to liga, "$user";


CREATE FUNCTION ACTUALIZAR_PARTIDOS_GANADOS()
RETURNS TRIGGER AS $BODY$

BEGIN
   IF NEW.FINALIZADO = 'S'  THEN
         IF  NEW.MARCADOR_LOCAL > NEW.MARCADOR_VISITANTE THEN
   
         UPDATE EQUIPOS
		 SET P_GANADOS = P_GANADOS +1
		 WHERE ID_EQUIPO = NEW.ID_LOCAL;
		 
	
	   
	     ELSEIF NEW.MARCADOR_LOCAL < NEW.MARCADOR_VISITANTE THEN
	   
	     UPDATE EQUIPOS
		 SET P_GANADOS = P_GANADOS +1
		 WHERE ID_EQUIPO = NEW.ID_VISITANTE;
	     
         END IF;	 
	 
		 
  END IF;

      RETURN NEW;
END;

$BODY$
LANGUAGE PLPGSQL;