set search_path to liga, "$user";

CREATE FUNCTION ACTUALIZAR_RESULTADO()
RETURNS TRIGGER AS $BODY$

BEGIN IF NEW.MARCADOR_LOCAL > NEW.MARCADOR_VISITANTE THEN
         NEW.RESULTADO := '1';
		 
	  ELSEIF NEW.MARCADOR_LOCAL = NEW.MARCADOR_VISITANTE THEN
	     NEW.RESULTADO := 'X';
	  ELSE
	     NEW.RESULTADO:='2';
		 
      END IF;

      RETURN NEW;
END;
$BODY$
LANGUAGE PLPGSQL;