set search_path to liga, "$user";

CREATE FUNCTION ACTUALIZAR_PARTIDOS_JUGADOS()
RETURNS TRIGGER AS $BODY$

BEGIN
IF NEW.FINALIZADO = 'S'  THEN
         UPDATE EQUIPOS
		 SET P_JUGADOS = P_JUGADOS +1
		 WHERE ID_EQUIPO IN (NEW.ID_LOCAL,NEW.ID_VISITANTE);
		 
	 
		 
      END IF;

      RETURN NEW;
END;
$BODY$
LANGUAGE PLPGSQL;