create database LIGA;
USE LIGA;

-- --------------------------------Cargamos el csv generado de la liga desde un periodico deportivo, desde el Table Date Import Wizard --------------------
-- ---------------------------------------------------------------------------------------------------------------------
 -- Alteramos la tabla para colocar la primary key de id_Equipo
     alter table equipos
     add constraint primary key (id_equipo);
     
  -- ------------------------------------------------Añadimos un campo nuevo a la tabla creada--------------------------------------------------------------
  
     alter table equipos
     add puesto int;
     
     
   -- ---------------Actualizamos la tabla para que el id_equipo tengas el mismo valor que el puesto y no salga null-------------------------------------------
    set global sql_safe_updates = 0;
    update equipos
	set puesto = id_equipo
    where id_equipo > 0;
    
    -- ------------------------------------------------ACTUALIZAMOS LAS TABLA EQUIPOS PARA PONERLA A CERO-------------------------------------------------------------------
    UPDATE EQUIPOS
		SET
			P_GANADOS	= 0,
			P_EMPATADOS	= 0,
			P_PERDIDOS	= 0,
			G_FAVOR		= 0,
			G_CONTRA	= 0,
			P_JUGADOS	= 0,
			PUNTOS 		= 0
			WHERE ID_EQUIPO > 0;
 
    
     -- Cramos la tabla partiodasd para poder generar ambas tablas
Drop table if exists partidos;
create table partidos 
  ( Id_Local int, 
    Id_Visitante int,
    Marcador_Local int default 0,
    Marcador_Visitante int default 0,
    Resultado char (1) default null,
    Jornada int,
    fecha date,
    primary key (Id_Local, Id_Visitante ),
    foreign key (Id_Local) references equipos(id_equipo),
	foreign key (Id_Visitante) references equipos(id_equipo)
    );
    
  -- ---------------------------------------------------------------------------------------------------------------------------------------------------
  -- -------------------------------------------------Insertamos los partidos de dos jornadas sin los resultados-----------------------------------------
 
 -- JORNADA 1:
-- ==========

INSERT INTO PARTIDOS VALUES (20,1,NULL, NULL, DEFAULT, 1, NULL);
INSERT INTO PARTIDOS VALUES (19,2,NULL, NULL, DEFAULT, 1, NULL);
INSERT INTO PARTIDOS VALUES (18,3,NULL, NULL, DEFAULT, 1, NULL);
INSERT INTO PARTIDOS VALUES (17,4,NULL, NULL, DEFAULT, 1, NULL);
INSERT INTO PARTIDOS VALUES (16,5,NULL, NULL, DEFAULT, 1, NULL);
INSERT INTO PARTIDOS VALUES (15,6,NULL, NULL, DEFAULT, 1, NULL);
INSERT INTO PARTIDOS VALUES (14,7,NULL, NULL, DEFAULT, 1, NULL);
INSERT INTO PARTIDOS VALUES (13,8,NULL, NULL, DEFAULT, 1, NULL);
INSERT INTO PARTIDOS VALUES (12,9,NULL, NULL, DEFAULT, 1, NULL);
INSERT INTO PARTIDOS VALUES (11,10,NULL, NULL, DEFAULT, 1, NULL);

CALL ACTUALIZAR_RESULTADO(20,1,1,3);
CALL ACTUALIZAR_RESULTADO(19,2,4,4);
CALL ACTUALIZAR_RESULTADO(18,3,3,3);
CALL ACTUALIZAR_RESULTADO(17,4,3,0);
CALL ACTUALIZAR_RESULTADO(16,5,3,0);
CALL ACTUALIZAR_RESULTADO(15,6,1,4);
CALL ACTUALIZAR_RESULTADO(14,7,4,1);
CALL ACTUALIZAR_RESULTADO(13,8,1,4);
CALL ACTUALIZAR_RESULTADO(12,9,4,1);
CALL ACTUALIZAR_RESULTADO(11,10,1,3);

-- JORNADA 2:
-- ==========

INSERT INTO PARTIDOS VALUES (2,1,NULL, NULL, DEFAULT, 2, NULL);
INSERT INTO PARTIDOS VALUES (20,3,NULL, NULL, DEFAULT, 2, NULL);
INSERT INTO PARTIDOS VALUES (19,4,NULL, NULL, DEFAULT, 2, NULL);
INSERT INTO PARTIDOS VALUES (18,5,NULL, NULL, DEFAULT, 2, NULL);
INSERT INTO PARTIDOS VALUES (17,6,NULL, NULL, DEFAULT, 2, NULL);
INSERT INTO PARTIDOS VALUES (16,7,NULL, NULL, DEFAULT, 2, NULL);
INSERT INTO PARTIDOS VALUES (15,8,NULL, NULL, DEFAULT, 2, NULL);
INSERT INTO PARTIDOS VALUES (14,9,NULL, NULL, DEFAULT, 2, NULL);
INSERT INTO PARTIDOS VALUES (13,10,NULL, NULL, DEFAULT, 2, NULL);
INSERT INTO PARTIDOS VALUES (12,11,NULL, NULL, DEFAULT, 2, NULL);

CALL ACTUALIZAR_RESULTADO(2 ,1,0,4 );
CALL ACTUALIZAR_RESULTADO(20,3,1,2 );
CALL ACTUALIZAR_RESULTADO(19,4,3,3 );
CALL ACTUALIZAR_RESULTADO(18,5,4,2 );
CALL ACTUALIZAR_RESULTADO(17,6,0,0 );
CALL ACTUALIZAR_RESULTADO(16,7,2,2 );
CALL ACTUALIZAR_RESULTADO(15,8,3,0 );
CALL ACTUALIZAR_RESULTADO(14,9,2,0 );
CALL ACTUALIZAR_RESULTADO(13,10,4,2 );
CALL ACTUALIZAR_RESULTADO(12,11,1,2 );

-- JORNADA 3:

INSERT INTO PARTIDOS VALUES (3 ,1, NULL, NULL, DEFAULT, 3, NULL);
INSERT INTO PARTIDOS VALUES (2 ,4, NULL, NULL, DEFAULT, 3, NULL);
INSERT INTO PARTIDOS VALUES (20,5, NULL, NULL, DEFAULT, 3, NULL);
INSERT INTO PARTIDOS VALUES (19,6, NULL, NULL, DEFAULT, 3, NULL);
INSERT INTO PARTIDOS VALUES (18,7, NULL, NULL, DEFAULT, 3, NULL);
INSERT INTO PARTIDOS VALUES (17,8, NULL, NULL, DEFAULT, 3, NULL);
INSERT INTO PARTIDOS VALUES (16,9, NULL, NULL, DEFAULT, 3, NULL);
INSERT INTO PARTIDOS VALUES (15,10, NULL, NULL, DEFAULT, 3, NULL);
INSERT INTO PARTIDOS VALUES (14,11, NULL, NULL, DEFAULT, 3, NULL);
INSERT INTO PARTIDOS VALUES (13,12, NULL, NULL, DEFAULT, 3, NULL);

CALL ACTUALIZAR_RESULTADO(3 ,1 ,4,2);
CALL ACTUALIZAR_RESULTADO(2 ,4 ,2,3);
CALL ACTUALIZAR_RESULTADO(20,5 ,0,4);
CALL ACTUALIZAR_RESULTADO(19,6 ,0,0);
CALL ACTUALIZAR_RESULTADO(18,7 ,4,4);
CALL ACTUALIZAR_RESULTADO(17,8 ,2,3);
CALL ACTUALIZAR_RESULTADO(16,9 ,3,0);
CALL ACTUALIZAR_RESULTADO(15,10,1,0);
CALL ACTUALIZAR_RESULTADO(14,11,0,4);
CALL ACTUALIZAR_RESULTADO(13,12,1,1);


-- JORNADA 4:

INSERT INTO PARTIDOS VALUES (4,1, NULL, NULL, DEFAULT, 4, NULL);
INSERT INTO PARTIDOS VALUES (3,5, NULL, NULL, DEFAULT, 4, NULL);
INSERT INTO PARTIDOS VALUES (2,6, NULL, NULL, DEFAULT, 4, NULL);
INSERT INTO PARTIDOS VALUES (20,7, NULL, NULL, DEFAULT, 4, NULL);
INSERT INTO PARTIDOS VALUES (19,8, NULL, NULL, DEFAULT, 4, NULL);
INSERT INTO PARTIDOS VALUES (18,9, NULL, NULL, DEFAULT, 4, NULL);
INSERT INTO PARTIDOS VALUES (17,10, NULL, NULL, DEFAULT, 4, NULL);
INSERT INTO PARTIDOS VALUES (16,11, NULL, NULL, DEFAULT, 4, NULL);
INSERT INTO PARTIDOS VALUES (15,12, NULL, NULL, DEFAULT, 4, NULL);
INSERT INTO PARTIDOS VALUES (14,13, NULL, NULL, DEFAULT, 4, NULL);

CALL ACTUALIZAR_RESULTADO(4, 1 ,1,4);
CALL ACTUALIZAR_RESULTADO(3, 5 ,1,0);
CALL ACTUALIZAR_RESULTADO(2, 6 ,1,0);
CALL ACTUALIZAR_RESULTADO(20,7 ,1,2);
CALL ACTUALIZAR_RESULTADO(19,8 ,3,1);
CALL ACTUALIZAR_RESULTADO(18,9 ,0,1);
CALL ACTUALIZAR_RESULTADO(17,10,1,4);
CALL ACTUALIZAR_RESULTADO(16,11,2,1);
CALL ACTUALIZAR_RESULTADO(15,12,4,4);
CALL ACTUALIZAR_RESULTADO(14,13,1,1);

-- JORNADA 5:

INSERT INTO PARTIDOS VALUES (5,1, NULL, NULL, DEFAULT, 5, NULL);
INSERT INTO PARTIDOS VALUES (4,6, NULL, NULL, DEFAULT, 5, NULL);
INSERT INTO PARTIDOS VALUES (3,7, NULL, NULL, DEFAULT, 5, NULL);
INSERT INTO PARTIDOS VALUES (2,8, NULL, NULL, DEFAULT, 5, NULL);
INSERT INTO PARTIDOS VALUES (20,9, NULL, NULL, DEFAULT, 5, NULL);
INSERT INTO PARTIDOS VALUES (19,10, NULL, NULL, DEFAULT, 5, NULL);
INSERT INTO PARTIDOS VALUES (18,11, NULL, NULL, DEFAULT, 5, NULL);
INSERT INTO PARTIDOS VALUES (17,12, NULL, NULL, DEFAULT, 5, NULL);
INSERT INTO PARTIDOS VALUES (16,13, NULL, NULL, DEFAULT, 5, NULL);
INSERT INTO PARTIDOS VALUES (15,14, NULL, NULL, DEFAULT, 5, NULL);

CALL ACTUALIZAR_RESULTADO(5,1,2,2);
CALL ACTUALIZAR_RESULTADO(4,6,0,4);
CALL ACTUALIZAR_RESULTADO(3,7,2,2);
CALL ACTUALIZAR_RESULTADO(2,8,0,3);
CALL ACTUALIZAR_RESULTADO(20,9,0,4 );
CALL ACTUALIZAR_RESULTADO(19,10,0,2);
CALL ACTUALIZAR_RESULTADO(18,11,1,0);
CALL ACTUALIZAR_RESULTADO(17,12,3,4);
CALL ACTUALIZAR_RESULTADO(16,13,4,1);
CALL ACTUALIZAR_RESULTADO(15,14,2,3);

-- JORNADA 6
INSERT INTO PARTIDOS VALUES (6, 1, NULL, NULL, DEFAULT, 6, NULL);
INSERT INTO PARTIDOS VALUES (5, 7, NULL, NULL, DEFAULT, 6, NULL);
INSERT INTO PARTIDOS VALUES (4, 8, NULL, NULL, DEFAULT, 6, NULL);
INSERT INTO PARTIDOS VALUES (3, 9, NULL, NULL, DEFAULT, 6, NULL);
INSERT INTO PARTIDOS VALUES (2, 10, NULL, NULL, DEFAULT, 6, NULL);
INSERT INTO PARTIDOS VALUES (20, 11, NULL, NULL, DEFAULT, 6, NULL);
INSERT INTO PARTIDOS VALUES (19, 12, NULL, NULL, DEFAULT, 6, NULL);
INSERT INTO PARTIDOS VALUES (18, 13, NULL, NULL, DEFAULT, 6, NULL);
INSERT INTO PARTIDOS VALUES (17, 14, NULL, NULL, DEFAULT, 6, NULL);
INSERT INTO PARTIDOS VALUES (16, 15, NULL, NULL, DEFAULT, 6, NULL);

-- Aquí actualizo los resultados de las dos primeras jornadas
-- JORNADA 6
CALL ACTUALIZAR_RESULTADO(6, 1, 2, 1);
CALL ACTUALIZAR_RESULTADO(5 , 7, 1, 0);
CALL ACTUALIZAR_RESULTADO(4 , 8, 0, 1);
CALL ACTUALIZAR_RESULTADO(3 , 9, 0, 0);
CALL ACTUALIZAR_RESULTADO(2 , 10, 3, 0);
CALL ACTUALIZAR_RESULTADO(20 , 11, 0, 2);
CALL ACTUALIZAR_RESULTADO(7 , 17, 4, 1);
CALL ACTUALIZAR_RESULTADO(8 , 18, 0, 1);
CALL ACTUALIZAR_RESULTADO(9 , 19, 3, 3);
CALL ACTUALIZAR_RESULTADO(10, 20, 1, 1);

-- JORNADA 7
INSERT INTO PARTIDOS VALUES (7, 1, NULL, NULL, DEFAULT, 7, NULL);
INSERT INTO PARTIDOS VALUES (6, 8, NULL, NULL, DEFAULT, 7, NULL);
INSERT INTO PARTIDOS VALUES (5, 9, NULL, NULL, DEFAULT, 7, NULL);
INSERT INTO PARTIDOS VALUES (4, 10, NULL, NULL, DEFAULT, 7, NULL);
INSERT INTO PARTIDOS VALUES (3, 11, NULL, NULL, DEFAULT, 7, NULL);
INSERT INTO PARTIDOS VALUES (2, 12, NULL, NULL, DEFAULT, 7, NULL);
INSERT INTO PARTIDOS VALUES (20, 13, NULL, NULL, DEFAULT, 7, NULL);
INSERT INTO PARTIDOS VALUES (19, 14, NULL, NULL, DEFAULT, 7, NULL);
INSERT INTO PARTIDOS VALUES (18, 15, NULL, NULL, DEFAULT, 7, NULL);
INSERT INTO PARTIDOS VALUES (17, 16, NULL, NULL, DEFAULT, 7, NULL);

-- JORNADA 7
CALL ACTUALIZAR_RESULTADO(7, 1, 2, 0);
CALL ACTUALIZAR_RESULTADO(6, 8, 0, 1);
CALL ACTUALIZAR_RESULTADO(5, 9, 1, 1);
CALL ACTUALIZAR_RESULTADO(4, 10, 1, 3);
CALL ACTUALIZAR_RESULTADO(3, 11, 2, 0);
CALL ACTUALIZAR_RESULTADO(2, 12, 0, 0);
CALL ACTUALIZAR_RESULTADO(20, 13, 1, 0);
CALL ACTUALIZAR_RESULTADO(19, 14, 5, 1);
CALL ACTUALIZAR_RESULTADO(18, 915, 1, 2);
CALL ACTUALIZAR_RESULTADO(17, 16, 3, 3);

-- JORNADA 8
INSERT INTO PARTIDOS VALUES (8, 1, NULL, NULL, DEFAULT, 8, NULL);
INSERT INTO PARTIDOS VALUES (7, 9, NULL, NULL, DEFAULT, 8, NULL);
INSERT INTO PARTIDOS VALUES (6,10, NULL, NULL, DEFAULT, 8, NULL);
INSERT INTO PARTIDOS VALUES (5, 11, NULL, NULL, DEFAULT, 8, NULL);
INSERT INTO PARTIDOS VALUES (4, 12, NULL, NULL, DEFAULT, 8, NULL);
INSERT INTO PARTIDOS VALUES (3, 13, NULL, NULL, DEFAULT, 8, NULL);
INSERT INTO PARTIDOS VALUES (2, 14, NULL, NULL, DEFAULT, 8, NULL);
INSERT INTO PARTIDOS VALUES (20, 15, NULL, NULL, DEFAULT, 8, NULL);
INSERT INTO PARTIDOS VALUES (19, 16, NULL, NULL, DEFAULT, 8, NULL);
INSERT INTO PARTIDOS VALUES (18, 17, NULL, NULL, DEFAULT, 8, NULL);

-- Aquí actualizo los resultados de las dos primeras jornadas
-- JORNADA 8
CALL ACTUALIZAR_RESULTADO(8, 1, 1, 1);
CALL ACTUALIZAR_RESULTADO(7 , 9, 2, 0);
CALL ACTUALIZAR_RESULTADO(6 , 10, 3, 1);
CALL ACTUALIZAR_RESULTADO(5 , 11, 0, 0);
CALL ACTUALIZAR_RESULTADO(4 , 12, 3, 4);
CALL ACTUALIZAR_RESULTADO(3 , 13, 1, 2);
CALL ACTUALIZAR_RESULTADO(2 , 14, 4, 0);
CALL ACTUALIZAR_RESULTADO(20 , 15, 1, 1);
CALL ACTUALIZAR_RESULTADO(19 , 16, 3, 2);
CALL ACTUALIZAR_RESULTADO(18, 17, 1, 0);

-- JORNADA 9
INSERT INTO PARTIDOS VALUES (9, 1, NULL, NULL, DEFAULT, 9, NULL);
INSERT INTO PARTIDOS VALUES (8, 10, NULL, NULL, DEFAULT, 9, NULL);
INSERT INTO PARTIDOS VALUES (7, 11, NULL, NULL, DEFAULT, 9, NULL);
INSERT INTO PARTIDOS VALUES (6, 12, NULL, NULL, DEFAULT, 9, NULL);
INSERT INTO PARTIDOS VALUES (5, 13, NULL, NULL, DEFAULT, 9, NULL);
INSERT INTO PARTIDOS VALUES (4, 14, NULL, NULL, DEFAULT, 9, NULL);
INSERT INTO PARTIDOS VALUES (3, 15, NULL, NULL, DEFAULT, 9, NULL);
INSERT INTO PARTIDOS VALUES (2, 16, NULL, NULL, DEFAULT, 9, NULL);
INSERT INTO PARTIDOS VALUES (20, 17, NULL, NULL, DEFAULT, 9, NULL);
INSERT INTO PARTIDOS VALUES (19, 18, NULL, NULL, DEFAULT, 9, NULL);

-- JORNADA 9
CALL ACTUALIZAR_RESULTADO(9, 1, 2, 2);
CALL ACTUALIZAR_RESULTADO(8, 10, 1, 1);
CALL ACTUALIZAR_RESULTADO(7, 11, 3, 1);
CALL ACTUALIZAR_RESULTADO(6, 12, 1, 0);
CALL ACTUALIZAR_RESULTADO(5, 13, 0, 2);
CALL ACTUALIZAR_RESULTADO(4, 14, 2, 0);
CALL ACTUALIZAR_RESULTADO(3, 15, 1, 0);
CALL ACTUALIZAR_RESULTADO(2, 16, 2, 1);
CALL ACTUALIZAR_RESULTADO(20, 17, 4, 2);
CALL ACTUALIZAR_RESULTADO(19, 18, 3, 0);

-- JORNADA 10
INSERT INTO PARTIDOS VALUES (10, 1, NULL, NULL, DEFAULT, 10, NULL);
INSERT INTO PARTIDOS VALUES (9, 11, NULL, NULL, DEFAULT, 10, NULL);
INSERT INTO PARTIDOS VALUES (8, 12, NULL, NULL, DEFAULT, 10, NULL);
INSERT INTO PARTIDOS VALUES (7, 13, NULL, NULL, DEFAULT, 10, NULL);
INSERT INTO PARTIDOS VALUES (6, 14, NULL, NULL, DEFAULT, 10, NULL);
INSERT INTO PARTIDOS VALUES (5, 15, NULL, NULL, DEFAULT, 10, NULL);
INSERT INTO PARTIDOS VALUES (4, 16, NULL, NULL, DEFAULT, 10, NULL);
INSERT INTO PARTIDOS VALUES (3, 17, NULL, NULL, DEFAULT, 10, NULL);
INSERT INTO PARTIDOS VALUES (2, 18, NULL, NULL, DEFAULT, 10, NULL);
INSERT INTO PARTIDOS VALUES (20, 19, NULL, NULL, DEFAULT,10, NULL);

-- JORNADA 10
CALL ACTUALIZAR_RESULTADO(10, 1, 3, 2);
CALL ACTUALIZAR_RESULTADO(9, 11, 1, 5);
CALL ACTUALIZAR_RESULTADO(8, 12, 0, 1);
CALL ACTUALIZAR_RESULTADO(7, 13, 1, 0);
CALL ACTUALIZAR_RESULTADO(6, 14, 0, 2);
CALL ACTUALIZAR_RESULTADO(5, 15, 3, 0);
CALL ACTUALIZAR_RESULTADO(4, 16, 2, 2);
CALL ACTUALIZAR_RESULTADO(3, 17, 2, 3);
CALL ACTUALIZAR_RESULTADO(2, 18, 3, 2);
CALL ACTUALIZAR_RESULTADO(20, 19, 4, 0);


-- JORNADA 11
INSERT INTO PARTIDOS VALUES(11, 1, NULL, NULL, DEFAULT, 11,  NULL);
INSERT INTO PARTIDOS VALUES(10, 12, NULL, NULL, DEFAULT, 11, NULL);
INSERT INTO PARTIDOS VALUES(9, 13, NULL, NULL, DEFAULT, 11,  NULL);
INSERT INTO PARTIDOS VALUES(8, 14, NULL, NULL, DEFAULT, 11,  NULL);
INSERT INTO PARTIDOS VALUES(7, 15, NULL, NULL, DEFAULT, 11,  NULL);
INSERT INTO PARTIDOS VALUES(6, 16, NULL, NULL, DEFAULT, 11,  NULL);
INSERT INTO PARTIDOS VALUES(5, 17, NULL, NULL, DEFAULT, 11,  NULL);
INSERT INTO PARTIDOS VALUES(4, 18, NULL, NULL, DEFAULT, 11,  NULL);
INSERT INTO PARTIDOS VALUES(3, 19, NULL, NULL, DEFAULT, 11,  NULL);
INSERT INTO PARTIDOS VALUES(2, 20,NULL, NULL, DEFAULT, 11,   NULL);
-- RESULTADOS JORNADA 11
CALL ACTUALIZAR_RESULTADO(11, 1, 2, 3);
CALL ACTUALIZAR_RESULTADO(10, 12, 2, 3);
CALL ACTUALIZAR_RESULTADO(9, 13, 3, 3);
CALL ACTUALIZAR_RESULTADO(8, 14, 2, 4);
CALL ACTUALIZAR_RESULTADO(7, 15, 1, 1);
CALL ACTUALIZAR_RESULTADO(6, 16, 2, 1);
CALL ACTUALIZAR_RESULTADO(5, 17, 3, 4);
CALL ACTUALIZAR_RESULTADO(4, 18, 3, 1);
CALL ACTUALIZAR_RESULTADO(3, 19, 3, 5);
CALL ACTUALIZAR_RESULTADO(2, 20, 3, 3);


--  JORNADA 12
INSERT INTO PARTIDOS VALUES(12, 1, NULL, NULL, DEFAULT, 12,  NULL);
INSERT INTO PARTIDOS VALUES(11, 13, NULL, NULL, DEFAULT, 12, NULL);
INSERT INTO PARTIDOS VALUES(10, 14, NULL, NULL, DEFAULT, 12, NULL);
INSERT INTO PARTIDOS VALUES(9, 15, NULL, NULL, DEFAULT, 12,  NULL);
INSERT INTO PARTIDOS VALUES(8, 16, NULL, NULL, DEFAULT, 12,  NULL);
INSERT INTO PARTIDOS VALUES(7, 17, NULL, NULL, DEFAULT, 12,  NULL);
INSERT INTO PARTIDOS VALUES(6, 18, NULL, NULL, DEFAULT, 12,  NULL);
INSERT INTO PARTIDOS VALUES(5, 19, NULL, NULL, DEFAULT, 12,  NULL);
INSERT INTO PARTIDOS VALUES(4, 20, NULL, NULL, DEFAULT, 12,  NULL);
INSERT INTO PARTIDOS VALUES(3, 2,NULL, NULL, DEFAULT, 12,    NULL);
-- RESULTADOS JORNADA 12
CALL ACTUALIZAR_RESULTADO(12, 1, 2, 2);
CALL ACTUALIZAR_RESULTADO(11, 13, 3, 3);
CALL ACTUALIZAR_RESULTADO(10, 14, 3, 4);
CALL ACTUALIZAR_RESULTADO(9, 15, 2, 4);
CALL ACTUALIZAR_RESULTADO(8, 16, 1, 1);
CALL ACTUALIZAR_RESULTADO(7, 17, 2, 1);
CALL ACTUALIZAR_RESULTADO(6, 18, 3, 4);
CALL ACTUALIZAR_RESULTADO(5, 19, 3, 1);
CALL ACTUALIZAR_RESULTADO(4, 20, 3, 5);
CALL ACTUALIZAR_RESULTADO(3, 2, 3, 3);


-- JORNADA 13
INSERT INTO PARTIDOS VALUES(13, 1, NULL, NULL, DEFAULT, 13,   NULL);
INSERT INTO PARTIDOS VALUES(12, 14, NULL, NULL, DEFAULT, 13,  NULL);
INSERT INTO PARTIDOS VALUES(11, 15, NULL, NULL, DEFAULT, 13,  NULL);
INSERT INTO PARTIDOS VALUES(10, 16, NULL, NULL, DEFAULT, 13,  NULL);
INSERT INTO PARTIDOS VALUES(9, 17, NULL, NULL, DEFAULT, 13,   NULL);
INSERT INTO PARTIDOS VALUES(8, 18, NULL, NULL, DEFAULT, 13,   NULL);
INSERT INTO PARTIDOS VALUES(7, 19, NULL, NULL, DEFAULT, 13,   NULL);
INSERT INTO PARTIDOS VALUES(6, 20, NULL, NULL, DEFAULT, 13,   NULL);
INSERT INTO PARTIDOS VALUES(5, 2, NULL, NULL, DEFAULT, 13,    NULL);
INSERT INTO PARTIDOS VALUES(4, 3,NULL, NULL, DEFAULT, 13,     NULL);
-- RESULTADOS JORNADA 13
CALL ACTUALIZAR_RESULTADO(13, 1, 2, 2);
CALL ACTUALIZAR_RESULTADO(12, 14, 4, 3);
CALL ACTUALIZAR_RESULTADO(11, 15, 5, 3);
CALL ACTUALIZAR_RESULTADO(10, 16, 2, 4);
CALL ACTUALIZAR_RESULTADO(9, 17, 1, 1);
CALL ACTUALIZAR_RESULTADO(8, 18, 3, 1);
CALL ACTUALIZAR_RESULTADO(7, 19, 3, 5);
CALL ACTUALIZAR_RESULTADO(6, 20, 6, 1);
CALL ACTUALIZAR_RESULTADO(5, 2, 4, 5);
CALL ACTUALIZAR_RESULTADO(4, 3, 2, 3);


-- JORNADA 14
INSERT INTO PARTIDOS VALUES(14, 1, NULL, NULL, DEFAULT, 14,  NULL);
INSERT INTO PARTIDOS VALUES(13, 15, NULL, NULL, DEFAULT, 14, NULL);
INSERT INTO PARTIDOS VALUES(12, 16, NULL, NULL, DEFAULT, 14, NULL);
INSERT INTO PARTIDOS VALUES(11, 17, NULL, NULL, DEFAULT, 14, NULL);
INSERT INTO PARTIDOS VALUES(10, 18, NULL, NULL, DEFAULT, 14, NULL);
INSERT INTO PARTIDOS VALUES(9, 19, NULL, NULL, DEFAULT, 14,  NULL);
INSERT INTO PARTIDOS VALUES(8, 20, NULL, NULL, DEFAULT, 14,  NULL);
INSERT INTO PARTIDOS VALUES(7, 2, NULL, NULL, DEFAULT, 14,   NULL);
INSERT INTO PARTIDOS VALUES(6, 3, NULL, NULL, DEFAULT, 14,   NULL);
INSERT INTO PARTIDOS VALUES(5, 4,NULL, NULL, DEFAULT, 14,    NULL);
-- RESULTADOS JORNADA 14
CALL ACTUALIZAR_RESULTADO(14, 1, 4, 3);
CALL ACTUALIZAR_RESULTADO(13, 15, 2, 2);
CALL ACTUALIZAR_RESULTADO(12, 16, 2, 4);
CALL ACTUALIZAR_RESULTADO(11, 17, 2, 3);
CALL ACTUALIZAR_RESULTADO(10, 18, 1, 2);
CALL ACTUALIZAR_RESULTADO(9, 19, 1, 1);
CALL ACTUALIZAR_RESULTADO(8, 20, 2, 4);
CALL ACTUALIZAR_RESULTADO(7, 2, 3, 3);
CALL ACTUALIZAR_RESULTADO(6, 3, 2, 5);
CALL ACTUALIZAR_RESULTADO(5, 4, 3, 2);


-- JORNADA 15
INSERT INTO PARTIDOS VALUES(15, 1, NULL, NULL, DEFAULT, 15,  NULL);
INSERT INTO PARTIDOS VALUES(14, 16, NULL, NULL, DEFAULT, 15, NULL);
INSERT INTO PARTIDOS VALUES(13, 17, NULL, NULL, DEFAULT, 15, NULL);
INSERT INTO PARTIDOS VALUES(12, 18, NULL, NULL, DEFAULT, 15, NULL);
INSERT INTO PARTIDOS VALUES(11, 19, NULL, NULL, DEFAULT, 15, NULL);
INSERT INTO PARTIDOS VALUES(10, 20, NULL, NULL, DEFAULT, 15, NULL);
INSERT INTO PARTIDOS VALUES(9, 2, NULL, NULL, DEFAULT, 15,   NULL);
INSERT INTO PARTIDOS VALUES(8, 3, NULL, NULL, DEFAULT, 15,   NULL);
INSERT INTO PARTIDOS VALUES(7, 4, NULL, NULL, DEFAULT, 15,   NULL);
INSERT INTO PARTIDOS VALUES(6, 5, NULL, NULL, DEFAULT, 15,   NULL);
-- RESULTADOS JORNADA 15
CALL ACTUALIZAR_RESULTADO(15, 1, 2, 4);
CALL ACTUALIZAR_RESULTADO(14, 16, 3, 3);
CALL ACTUALIZAR_RESULTADO(13, 17, 2, 1);
CALL ACTUALIZAR_RESULTADO(12, 18, 1, 3);
CALL ACTUALIZAR_RESULTADO(11, 19, 0, 1);
CALL ACTUALIZAR_RESULTADO(10, 20, 2, 1);
CALL ACTUALIZAR_RESULTADO(9, 2, 3, 4);
CALL ACTUALIZAR_RESULTADO(8, 3, 3, 1);
CALL ACTUALIZAR_RESULTADO(7, 4, 3, 4);
CALL ACTUALIZAR_RESULTADO(6, 5, 2, 3);

-- JORNADA 16
INSERT INTO PARTIDOS VALUES (16, 1,  NULL, NULL, DEFAULT, 16,  NULL);   
INSERT INTO PARTIDOS VALUES (15, 17, NULL, NULL, DEFAULT, 16,  NULL);
INSERT INTO PARTIDOS VALUES	(14, 18,  NULL, NULL, DEFAULT, 16,  NULL);
INSERT INTO PARTIDOS VALUES	(13, 19, NULL, NULL, DEFAULT, 16,  NULL);
INSERT INTO PARTIDOS VALUES	(12, 20, NULL, NULL, DEFAULT, 16,  NULL);
INSERT INTO PARTIDOS VALUES (11, 2,  NULL, NULL, DEFAULT, 16,  NULL);
INSERT INTO PARTIDOS VALUES	(10, 3,  NULL, NULL, DEFAULT, 16,  NULL);
INSERT INTO PARTIDOS VALUES	(9,  4,  NULL, NULL, DEFAULT, 16,  NULL);
INSERT INTO PARTIDOS VALUES	(8,  5,  NULL, NULL, DEFAULT, 16,  NULL);
INSERT INTO PARTIDOS VALUES	(7,  6,  NULL, NULL, DEFAULT, 16,  NULL);


CALL ACTUALIZAR_RESULTADO (16, 1,  1, 2 ); 
CALL ACTUALIZAR_RESULTADO (15, 17, 4, 0 ); 
CALL ACTUALIZAR_RESULTADO (14, 18, 0, 0 ); 
CALL ACTUALIZAR_RESULTADO (13, 19, 2, 0 ); 
CALL ACTUALIZAR_RESULTADO (12, 20, 0, 2 ); 
CALL ACTUALIZAR_RESULTADO (11, 2,  0, 0 ); 
CALL ACTUALIZAR_RESULTADO (10, 3,  0, 3 ); 
CALL ACTUALIZAR_RESULTADO (9,  4,  3, 0 ); 
CALL ACTUALIZAR_RESULTADO (8,  5,  1, 1 ); 
CALL ACTUALIZAR_RESULTADO (7,  6,  4, 0 ); 

-- JORNADA 17

INSERT INTO PARTIDOS VALUES (17, 1,  NULL, NULL, DEFAULT, 17,  NULL);
INSERT INTO PARTIDOS VALUES (16, 18, NULL, NULL, DEFAULT, 17,  NULL);
INSERT INTO PARTIDOS VALUES	(15, 19, NULL, NULL, DEFAULT, 17,  NULL);
INSERT INTO PARTIDOS VALUES	(14, 20, NULL, NULL, DEFAULT, 17,  NULL);
INSERT INTO PARTIDOS VALUES	(13, 2,  NULL, NULL, DEFAULT, 17,  NULL);
INSERT INTO PARTIDOS VALUES (12, 3,	 NULL, NULL, DEFAULT, 17,  NULL);
INSERT INTO PARTIDOS VALUES	(11, 4,	 NULL, NULL, DEFAULT, 17,  NULL);
INSERT INTO PARTIDOS VALUES	(10, 5,	 NULL, NULL, DEFAULT, 17,  NULL);
INSERT INTO PARTIDOS VALUES	(9,  6,	 NULL, NULL, DEFAULT, 17,  NULL);
INSERT INTO PARTIDOS VALUES	(8,  7,	 NULL, NULL, DEFAULT, 17,  NULL);

CALL ACTUALIZAR_RESULTADO (17, 1, 2, 2 ); 
CALL ACTUALIZAR_RESULTADO (16, 18, 0, 0 ); 
CALL ACTUALIZAR_RESULTADO (15, 19, 3, 0 ); 
CALL ACTUALIZAR_RESULTADO (14, 20, 1, 0 ); 
CALL ACTUALIZAR_RESULTADO (13, 2, 4, 2 ); 
CALL ACTUALIZAR_RESULTADO (12, 3,  1, 0 ); 
CALL ACTUALIZAR_RESULTADO (11, 4,  1, 3 ); 
CALL ACTUALIZAR_RESULTADO (10, 5,  3, 0 ); 
CALL ACTUALIZAR_RESULTADO (9,  6,  2, 1 ); 
CALL ACTUALIZAR_RESULTADO (8,  7,  1, 0 ); 



-- JORNADA 18




INSERT INTO PARTIDOS VALUES ( 18, 1,  NULL, NULL, DEFAULT, 18,  NULL);
INSERT INTO PARTIDOS VALUES ( 17, 19, NULL, NULL, DEFAULT, 18,  NULL);
INSERT INTO PARTIDOS VALUES	( 16, 20, NULL, NULL, DEFAULT, 18,  NULL);
INSERT INTO PARTIDOS VALUES	( 15, 2,  NULL, NULL, DEFAULT, 18,  NULL);
INSERT INTO PARTIDOS VALUES	( 14, 3,  NULL, NULL, DEFAULT, 18,  NULL);
INSERT INTO PARTIDOS VALUES ( 13, 4,  NULL, NULL, DEFAULT, 18,  NULL);
INSERT INTO PARTIDOS VALUES	( 12, 5,  NULL, NULL, DEFAULT, 18,  NULL);
INSERT INTO PARTIDOS VALUES	( 11, 6,  NULL, NULL, DEFAULT, 18,  NULL);
INSERT INTO PARTIDOS VALUES	( 10, 7,  NULL, NULL, DEFAULT, 18,  NULL);
INSERT INTO PARTIDOS VALUES	( 9,  8,  NULL, NULL, DEFAULT, 18,  NULL);


CALL ACTUALIZAR_RESULTADO (18, 1, 2, 1 ); 
CALL ACTUALIZAR_RESULTADO (17, 19, 0, 3 ); 
CALL ACTUALIZAR_RESULTADO (16, 20, 3, 2); 
CALL ACTUALIZAR_RESULTADO (15, 2, 1, 2); 
CALL ACTUALIZAR_RESULTADO (14, 3, 4, 1 ); 
CALL ACTUALIZAR_RESULTADO (13, 4,  1, 3 ); 
CALL ACTUALIZAR_RESULTADO (12, 5,  1, 1 ); 
CALL ACTUALIZAR_RESULTADO (11, 6,  3, 2 ); 
CALL ACTUALIZAR_RESULTADO (10, 7,  2, 3 ); 
CALL ACTUALIZAR_RESULTADO (9,  8,  1, 4 ); 


-- JORNADA 19

INSERT INTO PARTIDOS VALUES (19, 1, NULL, NULL, DEFAULT, 19,  NULL);
INSERT INTO PARTIDOS VALUES (18, 20, NULL, NULL, DEFAULT, 19,  NULL);
INSERT INTO PARTIDOS VALUES	(17, 2, NULL, NULL, DEFAULT, 19,  NULL);
INSERT INTO PARTIDOS VALUES	(16, 3, NULL, NULL, DEFAULT, 19,  NULL);
INSERT INTO PARTIDOS VALUES	(15, 4, NULL, NULL, DEFAULT, 19,  NULL);
INSERT INTO PARTIDOS VALUES (14, 5, NULL, NULL, DEFAULT, 19,  NULL);
INSERT INTO PARTIDOS VALUES	(13, 6, NULL, NULL, DEFAULT, 19,  NULL);
INSERT INTO PARTIDOS VALUES	(12, 7, NULL, NULL, DEFAULT, 19,  NULL);
INSERT INTO PARTIDOS VALUES	(11, 8, NULL, NULL, DEFAULT, 19,  NULL);
INSERT INTO PARTIDOS VALUES	(10, 9, NULL, NULL, DEFAULT, 19,  NULL);


CALL ACTUALIZAR_RESULTADO (19, 1, 1, 1 ); 
CALL ACTUALIZAR_RESULTADO (18, 20, 2, 3 ); 
CALL ACTUALIZAR_RESULTADO (17, 2, 4, 2); 
CALL ACTUALIZAR_RESULTADO (16, 3, 0, 2); 
CALL ACTUALIZAR_RESULTADO (15, 4, 2, 1 ); 
CALL ACTUALIZAR_RESULTADO (14, 5,  3, 3 ); 
CALL ACTUALIZAR_RESULTADO (13, 6,  2, 1 ); 
CALL ACTUALIZAR_RESULTADO (12, 7,  1, 2 ); 
CALL ACTUALIZAR_RESULTADO (11, 8,  0, 3 ); 
CALL ACTUALIZAR_RESULTADO (10, 9,  4, 4 ); 

-- JORNADA 20

INSERT INTO PARTIDOS VALUES (1,20, NULL, NULL, DEFAULT, 20,  NULL);
INSERT INTO PARTIDOS VALUES (2,19, NULL, NULL, DEFAULT, 20,  NULL);
INSERT INTO PARTIDOS VALUES	(3,18, NULL, NULL, DEFAULT, 20,  NULL);
INSERT INTO PARTIDOS VALUES	(4,17, NULL, NULL, DEFAULT, 20,  NULL);
INSERT INTO PARTIDOS VALUES	(5,16, NULL, NULL, DEFAULT, 20,  NULL);
INSERT INTO PARTIDOS VALUES (6,15, NULL, NULL, DEFAULT, 20,  NULL);
INSERT INTO PARTIDOS VALUES	(7,14, NULL, NULL, DEFAULT, 20,  NULL);
INSERT INTO PARTIDOS VALUES	(8,13, NULL, NULL, DEFAULT, 20,  NULL);
INSERT INTO PARTIDOS VALUES	(9,12, NULL, NULL, DEFAULT, 20,  NULL);
INSERT INTO PARTIDOS VALUES	(10,11, NULL, NULL, DEFAULT,20,  NULL);

CALL ACTUALIZAR_RESULTADO (1,20, 1, 2 ); 
CALL ACTUALIZAR_RESULTADO (2,19, 2, 1 ); 
CALL ACTUALIZAR_RESULTADO (3,18, 4, 3); 
CALL ACTUALIZAR_RESULTADO (4,17, 0, 0); 
CALL ACTUALIZAR_RESULTADO (5,16, 2, 2 ); 
CALL ACTUALIZAR_RESULTADO (6,15,  3,4 ); 
CALL ACTUALIZAR_RESULTADO (7,14,  2, 2 ); 
CALL ACTUALIZAR_RESULTADO (8,13,  1, 1 ); 
CALL ACTUALIZAR_RESULTADO (9,12,  0, 0 ); 
CALL ACTUALIZAR_RESULTADO (10,11,  4, 2 ); 




 -- JORNADA 21
INSERT INTO PARTIDOS VALUES (1, 2, NULL, NULL, DEFAULT,  21, NULL);
INSERT INTO PARTIDOS VALUES (3, 20, NULL, NULL, DEFAULT, 21, NULL);
INSERT INTO PARTIDOS VALUES (4, 19, NULL, NULL, DEFAULT, 21, NULL);
INSERT INTO PARTIDOS VALUES (5, 18, NULL, NULL, DEFAULT, 21, NULL);
INSERT INTO PARTIDOS VALUES (6, 17, NULL, NULL, DEFAULT, 21, NULL);
INSERT INTO PARTIDOS VALUES (7, 16, NULL, NULL, DEFAULT, 21, NULL);
INSERT INTO PARTIDOS VALUES (8, 15, NULL, NULL, DEFAULT, 21, NULL);
INSERT INTO PARTIDOS VALUES (9, 14, NULL, NULL, DEFAULT, 21, NULL);
INSERT INTO PARTIDOS VALUES (10, 13, NULL, NULL, DEFAULT, 21, NULL);
INSERT INTO PARTIDOS VALUES (11, 12, NULL, NULL, DEFAULT, 21, NULL);

-- JORNADA 21
CALL ACTUALIZAR_RESULTADO(1, 2,   3, 1);
CALL ACTUALIZAR_RESULTADO(3, 20,  3, 2);
CALL ACTUALIZAR_RESULTADO(4, 19,  1, 3);
CALL ACTUALIZAR_RESULTADO(5, 18,  4, 0);
CALL ACTUALIZAR_RESULTADO(6, 17,  3, 1);
CALL ACTUALIZAR_RESULTADO(7, 16,  4, 0);
CALL ACTUALIZAR_RESULTADO(8, 15,  0, 0);
CALL ACTUALIZAR_RESULTADO(9, 14,  0, 1);
CALL ACTUALIZAR_RESULTADO(10, 13, 3, 4);
CALL ACTUALIZAR_RESULTADO(11, 12,  2, 1);

-- JORNADA 22
INSERT INTO PARTIDOS VALUES (1, 3, NULL, NULL, DEFAULT, 22, NULL);
INSERT INTO PARTIDOS VALUES (4, 2, NULL, NULL, DEFAULT, 22 , NULL);
INSERT INTO PARTIDOS VALUES (5, 20, NULL, NULL, DEFAULT,22 , NULL);
INSERT INTO PARTIDOS VALUES (6, 19, NULL, NULL, DEFAULT, 22, NULL);
INSERT INTO PARTIDOS VALUES (7, 18, NULL, NULL, DEFAULT ,22, NULL);
INSERT INTO PARTIDOS VALUES (8, 17, NULL, NULL, DEFAULT, 22, NULL);
INSERT INTO PARTIDOS VALUES (9, 16, NULL, NULL, DEFAULT,22 , NULL);
INSERT INTO PARTIDOS VALUES (10, 15, NULL, NULL,DEFAULT,22 , NULL);
INSERT INTO PARTIDOS VALUES (11, 14, NULL, NULL,DEFAULT,22 , NULL);
INSERT INTO PARTIDOS VALUES (12, 13, NULL, NULL,DEFAULT,22 , NULL);



-- JORNADA 22
CALL ACTUALIZAR_RESULTADO(1, 3,  3, 3);
CALL ACTUALIZAR_RESULTADO(4, 2,  3, 1);
CALL ACTUALIZAR_RESULTADO(5, 20, 1, 1);
CALL ACTUALIZAR_RESULTADO(6, 19, 4, 3);
CALL ACTUALIZAR_RESULTADO(7, 18, 3, 0);
CALL ACTUALIZAR_RESULTADO(8, 17, 4, 2);
CALL ACTUALIZAR_RESULTADO(9, 16, 0, 2);
CALL ACTUALIZAR_RESULTADO(10, 15, 0, 3);
CALL ACTUALIZAR_RESULTADO(11, 14, 3, 3);
CALL ACTUALIZAR_RESULTADO(12, 13, 2, 2);

-- JORNADA 23
INSERT INTO PARTIDOS VALUES (1,  4 , NULL, NULL, DEFAULT,23, NULL);
INSERT INTO PARTIDOS VALUES (5,  3 , NULL, NULL, DEFAULT,23, NULL);
INSERT INTO PARTIDOS VALUES (6,  2 , NULL, NULL, DEFAULT,23, NULL);
INSERT INTO PARTIDOS VALUES (7,  20, NULL, NULL, DEFAULT,23, NULL);
INSERT INTO PARTIDOS VALUES (8,  19, NULL, NULL, DEFAULT,23, NULL);
INSERT INTO PARTIDOS VALUES (9,  18, NULL, NULL, DEFAULT,23, NULL);
INSERT INTO PARTIDOS VALUES (10, 17, NULL, NULL, DEFAULT,23, NULL);
INSERT INTO PARTIDOS VALUES (11, 16, NULL, NULL, DEFAULT,23, NULL);
INSERT INTO PARTIDOS VALUES (12, 15, NULL, NULL, DEFAULT,23, NULL);
INSERT INTO PARTIDOS VALUES (13, 14, NULL, NULL, DEFAULT,23, NULL);



-- JORNADA 23
CALL ACTUALIZAR_RESULTADO(1,  4 , 2, 4);
CALL ACTUALIZAR_RESULTADO(5,  3 , 2, 0);
CALL ACTUALIZAR_RESULTADO(6,  2 , 0, 0);
CALL ACTUALIZAR_RESULTADO(7,  20, 3, 4);
CALL ACTUALIZAR_RESULTADO(8,  19, 4, 4);
CALL ACTUALIZAR_RESULTADO(9,  18, 3, 1);
CALL ACTUALIZAR_RESULTADO(10, 17, 1, 1);
CALL ACTUALIZAR_RESULTADO(11, 16, 1, 2);
CALL ACTUALIZAR_RESULTADO(12, 15, 4, 0);
CALL ACTUALIZAR_RESULTADO(13, 14, 3, 0);
    

-- JORNADA 24
INSERT INTO PARTIDOS VALUES (1, 5 , NULL, NULL, DEFAULT,24, NULL);
INSERT INTO PARTIDOS VALUES (6, 4 , NULL, NULL, DEFAULT,24, NULL);
INSERT INTO PARTIDOS VALUES (7, 3 , NULL, NULL, DEFAULT, 24, NULL);
INSERT INTO PARTIDOS VALUES (8,  2, NULL, NULL, DEFAULT, 24, NULL);
INSERT INTO PARTIDOS VALUES (9, 20, NULL, NULL, DEFAULT, 24, NULL);
INSERT INTO PARTIDOS VALUES (10, 19, NULL, NULL, DEFAULT, 24, NULL);
INSERT INTO PARTIDOS VALUES (11, 18, NULL, NULL, DEFAULT, 24, NULL);
INSERT INTO PARTIDOS VALUES (12, 17, NULL, NULL, DEFAULT, 24, NULL);
INSERT INTO PARTIDOS VALUES (13, 16, NULL, NULL, DEFAULT, 24, NULL);
INSERT INTO PARTIDOS VALUES (14, 15, NULL, NULL, DEFAULT, 24, NULL);



-- JORNADA 24
CALL ACTUALIZAR_RESULTADO(1 , 5 , 3, 0);
CALL ACTUALIZAR_RESULTADO(6 , 4 ,  3, 1);
CALL ACTUALIZAR_RESULTADO(7 , 3 ,  1, 2);
CALL ACTUALIZAR_RESULTADO(8 ,  2,  4, 3);
CALL ACTUALIZAR_RESULTADO(9 , 20,  3, 0);
CALL ACTUALIZAR_RESULTADO(10, 19, 4, 0);
CALL ACTUALIZAR_RESULTADO(11, 18, 0, 2);
CALL ACTUALIZAR_RESULTADO(12, 17, 0, 3);
CALL ACTUALIZAR_RESULTADO(13, 16, 3, 1);
CALL ACTUALIZAR_RESULTADO(14, 15, 2, 1);

-- JORNADA 25
INSERT INTO PARTIDOS VALUES (1 , 6 , NULL, NULL, DEFAULT,25, NULL);
INSERT INTO PARTIDOS VALUES (7 , 5 , NULL, NULL, DEFAULT,25, NULL);
INSERT INTO PARTIDOS VALUES (8 , 4 , NULL, NULL, DEFAULT, 25, NULL);
INSERT INTO PARTIDOS VALUES (9 , 3 , NULL, NULL, DEFAULT, 25, NULL);
INSERT INTO PARTIDOS VALUES (10, 2 , NULL, NULL, DEFAULT, 25, NULL);
INSERT INTO PARTIDOS VALUES (11, 20, NULL, NULL, DEFAULT, 25, NULL);
INSERT INTO PARTIDOS VALUES (12, 19, NULL, NULL, DEFAULT, 25, NULL);
INSERT INTO PARTIDOS VALUES (13, 18, NULL, NULL, DEFAULT, 25, NULL);
INSERT INTO PARTIDOS VALUES (14, 17, NULL, NULL, DEFAULT, 25, NULL);
INSERT INTO PARTIDOS VALUES (15, 16, NULL, NULL, DEFAULT, 25, NULL);



-- JORNADA 25
CALL ACTUALIZAR_RESULTADO(1 , 6 , 0, 4);
CALL ACTUALIZAR_RESULTADO(7 , 5 ,  0, 0);
CALL ACTUALIZAR_RESULTADO(8 , 4 ,  2, 0);
CALL ACTUALIZAR_RESULTADO(9 , 3 ,  0, 4);
CALL ACTUALIZAR_RESULTADO(10, 2 ,  4, 4);
CALL ACTUALIZAR_RESULTADO(11, 20, 0, 1);
CALL ACTUALIZAR_RESULTADO(12, 19, 2, 1);
CALL ACTUALIZAR_RESULTADO(13, 18, 1, 2);
CALL ACTUALIZAR_RESULTADO(14, 17, 4, 0);
CALL ACTUALIZAR_RESULTADO(15, 16, 3, 0);

-- JORNADA 26
INSERT INTO PARTIDOS VALUES (1,  7,  NULL, NULL, DEFAULT, 26, NULL);
INSERT INTO PARTIDOS VALUES (8,  6,  NULL, NULL, DEFAULT, 26, NULL);
INSERT INTO PARTIDOS VALUES (9,  5,  NULL, NULL, DEFAULT, 26, NULL);
INSERT INTO PARTIDOS VALUES (10, 4,  NULL, NULL, DEFAULT, 26, NULL);
INSERT INTO PARTIDOS VALUES (11, 3,  NULL, NULL, DEFAULT, 26, NULL);
INSERT INTO PARTIDOS VALUES (12, 2,  NULL, NULL, DEFAULT, 26, NULL);
INSERT INTO PARTIDOS VALUES (13, 20, NULL, NULL, DEFAULT, 26, NULL);
INSERT INTO PARTIDOS VALUES (14, 19, NULL, NULL, DEFAULT, 26, NULL);
INSERT INTO PARTIDOS VALUES (15, 18, NULL, NULL, DEFAULT, 26, NULL);
INSERT INTO PARTIDOS VALUES (16, 17, NULL, NULL, DEFAULT, 26, NULL);

-- RESULTADOS JORNADA 26
CALL ACTUALIZAR_RESULTADO(1,  7,  2, 3);
CALL ACTUALIZAR_RESULTADO(8,  6,  1, 4);
CALL ACTUALIZAR_RESULTADO(9,  5,  1, 4);
CALL ACTUALIZAR_RESULTADO(10, 4,  1, 1);
CALL ACTUALIZAR_RESULTADO(11, 3,  3, 4);
CALL ACTUALIZAR_RESULTADO(12, 2,  2, 4);
CALL ACTUALIZAR_RESULTADO(13, 20, 4, 1);
CALL ACTUALIZAR_RESULTADO(14, 19, 3, 3);
CALL ACTUALIZAR_RESULTADO(15, 18, 1, 4);
CALL ACTUALIZAR_RESULTADO(16, 17, 2, 3);


-- JORNADA 27
INSERT INTO PARTIDOS VALUES (1,  8,  NULL, NULL, DEFAULT, 27, NULL);
INSERT INTO PARTIDOS VALUES (9,  7,  NULL, NULL, DEFAULT, 27, NULL);
INSERT INTO PARTIDOS VALUES (10, 6,  NULL, NULL, DEFAULT, 27, NULL);
INSERT INTO PARTIDOS VALUES (11, 5,  NULL, NULL, DEFAULT, 27, NULL);
INSERT INTO PARTIDOS VALUES (12, 4,  NULL, NULL, DEFAULT, 27, NULL);
INSERT INTO PARTIDOS VALUES (13, 3,  NULL, NULL, DEFAULT, 27, NULL);
INSERT INTO PARTIDOS VALUES (14, 2,  NULL, NULL, DEFAULT, 27, NULL);
INSERT INTO PARTIDOS VALUES (15, 20, NULL, NULL, DEFAULT, 27, NULL);
INSERT INTO PARTIDOS VALUES (16, 19, NULL, NULL, DEFAULT, 27, NULL);
INSERT INTO PARTIDOS VALUES (17, 18, NULL, NULL, DEFAULT, 27, NULL);

-- RESULTADOS JORNADA 27
CALL ACTUALIZAR_RESULTADO(1,  8,  4, 0);
CALL ACTUALIZAR_RESULTADO(9,  7,  1, 3);
CALL ACTUALIZAR_RESULTADO(10, 6,  3, 1);
CALL ACTUALIZAR_RESULTADO(11, 5,  3, 3);
CALL ACTUALIZAR_RESULTADO(12, 4,  2, 4);
CALL ACTUALIZAR_RESULTADO(13, 3,  1, 2);
CALL ACTUALIZAR_RESULTADO(14, 2,  3, 1);
CALL ACTUALIZAR_RESULTADO(15, 20, 3, 2);
CALL ACTUALIZAR_RESULTADO(16, 19, 4, 1);
CALL ACTUALIZAR_RESULTADO(17, 18, 0, 2);


-- JORNADA 28
INSERT INTO PARTIDOS VALUES (1,  9,  NULL, NULL, DEFAULT, 28, NULL);
INSERT INTO PARTIDOS VALUES (10, 8,  NULL, NULL, DEFAULT, 28, NULL);
INSERT INTO PARTIDOS VALUES (11, 7,  NULL, NULL, DEFAULT, 28, NULL);
INSERT INTO PARTIDOS VALUES (12, 6,  NULL, NULL, DEFAULT, 28, NULL);
INSERT INTO PARTIDOS VALUES (13, 5,  NULL, NULL, DEFAULT, 28, NULL);
INSERT INTO PARTIDOS VALUES (14, 4,  NULL, NULL, DEFAULT, 28, NULL);
INSERT INTO PARTIDOS VALUES (15, 3,  NULL, NULL, DEFAULT, 28, NULL);
INSERT INTO PARTIDOS VALUES (16, 2,  NULL, NULL, DEFAULT, 28, NULL);
INSERT INTO PARTIDOS VALUES (17, 20, NULL, NULL, DEFAULT, 28, NULL);
INSERT INTO PARTIDOS VALUES (18, 19, NULL, NULL, DEFAULT, 28, NULL);

-- RESULTADOS JORNADA 28
CALL ACTUALIZAR_RESULTADO(1,  9,  0, 0);
CALL ACTUALIZAR_RESULTADO(10, 8,  2, 1);
CALL ACTUALIZAR_RESULTADO(11, 7,  0, 2);
CALL ACTUALIZAR_RESULTADO(12, 6,  0, 3);
CALL ACTUALIZAR_RESULTADO(13, 5,  1, 1);
CALL ACTUALIZAR_RESULTADO(14, 4,  2, 2);
CALL ACTUALIZAR_RESULTADO(15, 3,  4, 2);
CALL ACTUALIZAR_RESULTADO(16, 2,  3, 3);
CALL ACTUALIZAR_RESULTADO(17, 20, 2, 1);
CALL ACTUALIZAR_RESULTADO(18, 19, 0, 3);



-- JORNADA 29
INSERT INTO PARTIDOS VALUES (1,  10, NULL, NULL, DEFAULT, 29, NULL);
INSERT INTO PARTIDOS VALUES (11, 9,  NULL, NULL, DEFAULT, 29, NULL);
INSERT INTO PARTIDOS VALUES (12, 8,  NULL, NULL, DEFAULT, 29, NULL);
INSERT INTO PARTIDOS VALUES (13, 7,  NULL, NULL, DEFAULT, 29, NULL);
INSERT INTO PARTIDOS VALUES (14, 6,  NULL, NULL, DEFAULT, 29, NULL);
INSERT INTO PARTIDOS VALUES (15, 5,  NULL, NULL, DEFAULT, 29, NULL);
INSERT INTO PARTIDOS VALUES (16, 4,  NULL, NULL, DEFAULT, 29, NULL);
INSERT INTO PARTIDOS VALUES (17, 3,  NULL, NULL, DEFAULT, 29, NULL);
INSERT INTO PARTIDOS VALUES (18, 2,  NULL, NULL, DEFAULT, 29, NULL);
INSERT INTO PARTIDOS VALUES (19, 20, NULL, NULL, DEFAULT, 29, NULL);

-- RESULTADOS JORNADA 29
CALL ACTUALIZAR_RESULTADO(1,  10, 0, 2);
CALL ACTUALIZAR_RESULTADO(11,  9, 0, 3);
CALL ACTUALIZAR_RESULTADO(12,  8, 3, 0);
CALL ACTUALIZAR_RESULTADO(13,  7, 2, 2);
CALL ACTUALIZAR_RESULTADO(14,  6, 2, 4);
CALL ACTUALIZAR_RESULTADO(15,  5, 3, 1);
CALL ACTUALIZAR_RESULTADO(16,  4, 3, 3);
CALL ACTUALIZAR_RESULTADO(17,  3, 1, 4);
CALL ACTUALIZAR_RESULTADO(18,  2, 2, 1);
CALL ACTUALIZAR_RESULTADO(19, 20, 0, 2);



-- JORNADA 30
INSERT INTO PARTIDOS VALUES (1,  11, NULL, NULL, DEFAULT, 30, NULL);
INSERT INTO PARTIDOS VALUES (12, 10, NULL, NULL, DEFAULT, 30, NULL);
INSERT INTO PARTIDOS VALUES (13, 9,  NULL, NULL, DEFAULT, 30, NULL);
INSERT INTO PARTIDOS VALUES (14, 8,  NULL, NULL, DEFAULT, 30, NULL);
INSERT INTO PARTIDOS VALUES (15, 7,  NULL, NULL, DEFAULT, 30, NULL);
INSERT INTO PARTIDOS VALUES (16, 6,  NULL, NULL, DEFAULT, 30, NULL);
INSERT INTO PARTIDOS VALUES (17, 5,  NULL, NULL, DEFAULT, 30, NULL);
INSERT INTO PARTIDOS VALUES (18, 4,  NULL, NULL, DEFAULT, 30, NULL);
INSERT INTO PARTIDOS VALUES (19, 3,  NULL, NULL, DEFAULT, 30, NULL);
INSERT INTO PARTIDOS VALUES (20, 2,  NULL, NULL, DEFAULT, 30, NULL);

-- RESULTADOS JORNADA 30
CALL ACTUALIZAR_RESULTADO(1,  11, 3, 4);
CALL ACTUALIZAR_RESULTADO(12, 10, 0, 1);
CALL ACTUALIZAR_RESULTADO(13,  9, 4, 0);
CALL ACTUALIZAR_RESULTADO(14,  8, 0, 1);
CALL ACTUALIZAR_RESULTADO(15,  7, 3, 2);
CALL ACTUALIZAR_RESULTADO(16,  6, 0, 0);
CALL ACTUALIZAR_RESULTADO(17,  5, 1, 2);
CALL ACTUALIZAR_RESULTADO(18,  4, 1, 0);
CALL ACTUALIZAR_RESULTADO(19,  3, 0, 0);
CALL ACTUALIZAR_RESULTADO(20,  2, 4, 3);

-- JORNADA 31
INSERT INTO PARTIDOS VALUES(1, 12, NULL, NULL, DEFAULT,  31, NULL);
INSERT INTO PARTIDOS VALUES(13, 11, NULL, NULL, DEFAULT, 31, NULL);
INSERT INTO PARTIDOS VALUES(14, 10, NULL, NULL, DEFAULT, 31, NULL);
INSERT INTO PARTIDOS VALUES(15, 9, NULL, NULL, DEFAULT,  31, NULL);
INSERT INTO PARTIDOS VALUES(16, 8, NULL, NULL, DEFAULT,  31, NULL);
INSERT INTO PARTIDOS VALUES(17, 7, NULL, NULL, DEFAULT,  31, NULL);
INSERT INTO PARTIDOS VALUES(18, 6, NULL, NULL, DEFAULT,  31, NULL);
INSERT INTO PARTIDOS VALUES(19, 5, NULL, NULL, DEFAULT,  31, NULL);
INSERT INTO PARTIDOS VALUES(20, 4, NULL, NULL, DEFAULT,  31, NULL);
INSERT INTO PARTIDOS VALUES(2, 3, NULL, NULL, DEFAULT,   31, NULL);
CALL ACTUALIZAR_RESULTADO(1, 12, 1, 1);
CALL ACTUALIZAR_RESULTADO(13, 11,1, 0);
CALL ACTUALIZAR_RESULTADO(14, 10,3, 0);
CALL ACTUALIZAR_RESULTADO(15, 9, 0, 0);
CALL ACTUALIZAR_RESULTADO(16, 8, 4, 1);
CALL ACTUALIZAR_RESULTADO(17, 7, 3, 1);
CALL ACTUALIZAR_RESULTADO(18, 6, 2, 1);
CALL ACTUALIZAR_RESULTADO(19, 5, 4, 0);
CALL ACTUALIZAR_RESULTADO(20, 4, 2, 2);
CALL ACTUALIZAR_RESULTADO(2, 3,  4, 1);

-- JORNADA 32
INSERT INTO PARTIDOS VALUES(1, 13,  NULL, NULL,   DEFAULT, 32, NULL);
INSERT INTO PARTIDOS VALUES(14, 12, NULL, NULL,   DEFAULT, 32, NULL);
INSERT INTO PARTIDOS VALUES(15, 11, NULL, NULL,   DEFAULT, 32, NULL);
INSERT INTO PARTIDOS VALUES(16, 10,  NULL, NULL,   DEFAULT, 32, NULL);
INSERT INTO PARTIDOS VALUES(17, 9,  NULL, NULL,   DEFAULT, 32, NULL);
INSERT INTO PARTIDOS VALUES(18, 8,  NULL, NULL,   DEFAULT, 32, NULL);
INSERT INTO PARTIDOS VALUES(19, 7,  NULL, NULL,   DEFAULT, 32, NULL);
INSERT INTO PARTIDOS VALUES(20, 6,  NULL, NULL,   DEFAULT, 32, NULL);
INSERT INTO PARTIDOS VALUES(2, 5,  NULL, NULL,   DEFAULT, 32, NULL);
INSERT INTO PARTIDOS VALUES(3, 4,   NULL, NULL,   DEFAULT, 32, NULL);
CALL ACTUALIZAR_RESULTADO(1, 13,  1, 1);
CALL ACTUALIZAR_RESULTADO(14, 12, 1, 0);
CALL ACTUALIZAR_RESULTADO(15, 11, 3, 0);
CALL ACTUALIZAR_RESULTADO(16, 10, 0, 0);
CALL ACTUALIZAR_RESULTADO(17, 9,  4, 1);
CALL ACTUALIZAR_RESULTADO(18, 8,  3, 1);
CALL ACTUALIZAR_RESULTADO(19, 7,  2, 1);
CALL ACTUALIZAR_RESULTADO(20, 6,  4, 0);
CALL ACTUALIZAR_RESULTADO(2, 5,   2, 2);
CALL ACTUALIZAR_RESULTADO(3, 4,   4, 1);

-- JORNADA 33
INSERT INTO PARTIDOS VALUES(1, 14,  NULL, NULL,   DEFAULT, 33, NULL);
INSERT INTO PARTIDOS VALUES(15, 13, NULL, NULL,   DEFAULT, 33, NULL);
INSERT INTO PARTIDOS VALUES(16, 12, NULL, NULL,   DEFAULT, 33, NULL);
INSERT INTO PARTIDOS VALUES(17, 11, NULL, NULL,   DEFAULT, 33, NULL);
INSERT INTO PARTIDOS VALUES(18, 10, NULL, NULL,   DEFAULT, 33, NULL);
INSERT INTO PARTIDOS VALUES(19, 9,  NULL, NULL,   DEFAULT, 33, NULL);
INSERT INTO PARTIDOS VALUES(20, 8,  NULL, NULL,   DEFAULT, 33, NULL);
INSERT INTO PARTIDOS VALUES(2, 7,   NULL, NULL,   DEFAULT, 33, NULL);
INSERT INTO PARTIDOS VALUES(3, 6,   NULL, NULL,   DEFAULT, 33, NULL);
INSERT INTO PARTIDOS VALUES(4, 5,   NULL, NULL,   DEFAULT, 33, NULL);
CALL ACTUALIZAR_RESULTADO(1, 14,  2, 0);
CALL ACTUALIZAR_RESULTADO(15, 13, 1, 3);
CALL ACTUALIZAR_RESULTADO(16, 12, 1, 4);
CALL ACTUALIZAR_RESULTADO(17, 11, 2, 2);
CALL ACTUALIZAR_RESULTADO(18, 10, 3, 2);
CALL ACTUALIZAR_RESULTADO(19, 9,  2, 0);
CALL ACTUALIZAR_RESULTADO(20, 8,  3, 4);
CALL ACTUALIZAR_RESULTADO(2, 7,   4, 2);
CALL ACTUALIZAR_RESULTADO(3, 6,   3, 3);
CALL ACTUALIZAR_RESULTADO(4, 5,   4, 4);

-- JORNADA 34
INSERT INTO PARTIDOS VALUES(1,	15, NULL, NULL,   DEFAULT, 34, NULL);
INSERT INTO PARTIDOS VALUES(16,	14, NULL, NULL,   DEFAULT, 34, NULL);
INSERT INTO PARTIDOS VALUES(17,	13, NULL, NULL,   DEFAULT, 34, NULL);
INSERT INTO PARTIDOS VALUES(18,	12, NULL, NULL,   DEFAULT, 34, NULL);
INSERT INTO PARTIDOS VALUES(19,	11, NULL, NULL,   DEFAULT, 34, NULL);
INSERT INTO PARTIDOS VALUES(20,	10, NULL, NULL,   DEFAULT, 34, NULL);
INSERT INTO PARTIDOS VALUES(2,	9, NULL, NULL,   DEFAULT,  34, NULL);
INSERT INTO PARTIDOS VALUES(3,	8, NULL, NULL,   DEFAULT,  34, NULL);
INSERT INTO PARTIDOS VALUES(4,	7, NULL, NULL,   DEFAULT,  34, NULL);
INSERT INTO PARTIDOS VALUES(5,	6, NULL, NULL,   DEFAULT,  34, NULL);
CALL ACTUALIZAR_RESULTADO(1, 15, 2, 0);
CALL ACTUALIZAR_RESULTADO(16, 14, 1, 1);
CALL ACTUALIZAR_RESULTADO(17, 13, 1, 0);
CALL ACTUALIZAR_RESULTADO(18, 12, 3, 3);
CALL ACTUALIZAR_RESULTADO(19, 11, 3, 4);
CALL ACTUALIZAR_RESULTADO(20, 10, 2, 3);
CALL ACTUALIZAR_RESULTADO(2,   9, 3, 1);
CALL ACTUALIZAR_RESULTADO(3,   8, 2, 4);
CALL ACTUALIZAR_RESULTADO(4,   7, 1, 0);
CALL ACTUALIZAR_RESULTADO(5,   6, 1, 2);
 
-- JORNADA 35
INSERT INTO PARTIDOS VALUES(1,  16, NULL, NULL,   DEFAULT, 35, NULL);
INSERT INTO PARTIDOS VALUES(17, 15, NULL, NULL,   DEFAULT, 35, NULL);
INSERT INTO PARTIDOS VALUES(18, 14, NULL, NULL,   DEFAULT, 35, NULL);
INSERT INTO PARTIDOS VALUES(19, 13, NULL, NULL,   DEFAULT, 35, NULL);
INSERT INTO PARTIDOS VALUES(20, 12, NULL, NULL,   DEFAULT, 35, NULL);
INSERT INTO PARTIDOS VALUES(2,  11, NULL, NULL,   DEFAULT, 35, NULL);
INSERT INTO PARTIDOS VALUES(3,  10, NULL, NULL,   DEFAULT, 35, NULL);
INSERT INTO PARTIDOS VALUES(4,  9,  NULL, NULL,   DEFAULT, 35, NULL);
INSERT INTO PARTIDOS VALUES(5,  8,  NULL, NULL,   DEFAULT, 35, NULL);
INSERT INTO PARTIDOS VALUES(6,  7,  NULL, NULL,   DEFAULT, 35, NULL);
CALL ACTUALIZAR_RESULTADO(1,  16, 1, 2);
CALL ACTUALIZAR_RESULTADO(17, 15, 2, 2);
CALL ACTUALIZAR_RESULTADO(18, 14, 4, 4);
CALL ACTUALIZAR_RESULTADO(19, 13, 4, 1);
CALL ACTUALIZAR_RESULTADO(20, 12, 2, 4);
CALL ACTUALIZAR_RESULTADO(2,  11, 0, 0);
CALL ACTUALIZAR_RESULTADO(3,  10, 3, 3);
CALL ACTUALIZAR_RESULTADO(4,  9,  1, 4);
CALL ACTUALIZAR_RESULTADO(5,  8,  3, 3);
CALL ACTUALIZAR_RESULTADO(6,  7,  0, 4);
 
-- JORNADA 36
INSERT INTO PARTIDOS VALUES(1, 17, NULL, NULL,   DEFAULT,  36, NULL);
INSERT INTO PARTIDOS VALUES(18, 16, NULL, NULL,   DEFAULT, 36, NULL);
INSERT INTO PARTIDOS VALUES(19, 15, NULL, NULL,   DEFAULT, 36, NULL);
INSERT INTO PARTIDOS VALUES(20, 14, NULL, NULL,   DEFAULT, 36, NULL);
INSERT INTO PARTIDOS VALUES(2, 13, NULL, NULL,   DEFAULT,  36, NULL);
INSERT INTO PARTIDOS VALUES(3, 12, NULL, NULL,   DEFAULT,  36, NULL);
INSERT INTO PARTIDOS VALUES(4, 11, NULL, NULL,   DEFAULT,  36, NULL);
INSERT INTO PARTIDOS VALUES(5, 10, NULL, NULL,   DEFAULT,  36, NULL);
INSERT INTO PARTIDOS VALUES(6, 9, NULL, NULL,   DEFAULT,   36, NULL);
INSERT INTO PARTIDOS VALUES(7, 8, NULL, NULL,   DEFAULT,   36, NULL);
CALL ACTUALIZAR_RESULTADO(1, 17,  4, 0);                   
CALL ACTUALIZAR_RESULTADO(18, 16, 1, 1);
CALL ACTUALIZAR_RESULTADO(19, 15, 3, 4);
CALL ACTUALIZAR_RESULTADO(20, 14, 3, 0);
CALL ACTUALIZAR_RESULTADO(2, 13,  1, 1);
CALL ACTUALIZAR_RESULTADO(3, 12,  0, 3);
CALL ACTUALIZAR_RESULTADO(4, 11,  2, 1);
CALL ACTUALIZAR_RESULTADO(5, 10,  4, 4);
CALL ACTUALIZAR_RESULTADO(6, 9,   0, 2);
CALL ACTUALIZAR_RESULTADO(7, 8,   4, 3); 
 
-- JORNADA 37
INSERT INTO PARTIDOS VALUES(1	, 18, NULL, NULL,   DEFAULT, 37, NULL);
INSERT INTO PARTIDOS VALUES(19	, 17, NULL, NULL,   DEFAULT, 37, NULL);
INSERT INTO PARTIDOS VALUES(20	, 16, NULL, NULL,   DEFAULT, 37, NULL);
INSERT INTO PARTIDOS VALUES(2	, 15, NULL, NULL,   DEFAULT, 37, NULL);
INSERT INTO PARTIDOS VALUES(3	, 14, NULL, NULL,   DEFAULT, 37, NULL);
INSERT INTO PARTIDOS VALUES(4	, 13, NULL, NULL,   DEFAULT, 37, NULL);
INSERT INTO PARTIDOS VALUES(5	, 12, NULL, NULL,   DEFAULT, 37, NULL);
INSERT INTO PARTIDOS VALUES(6	, 11, NULL, NULL,   DEFAULT, 37, NULL);
INSERT INTO PARTIDOS VALUES(7	, 10, NULL, NULL,   DEFAULT, 37, NULL);
INSERT INTO PARTIDOS VALUES(8	, 9 , NULL, NULL,   DEFAULT, 37, NULL);
CALL ACTUALIZAR_RESULTADO(1	, 18, 1, 2);
CALL ACTUALIZAR_RESULTADO(19, 17, 2, 2);
CALL ACTUALIZAR_RESULTADO(20, 16, 4, 4);
CALL ACTUALIZAR_RESULTADO(2	, 15, 4, 1);
CALL ACTUALIZAR_RESULTADO(3	, 14, 2, 4);
CALL ACTUALIZAR_RESULTADO(4	, 13, 0, 0);
CALL ACTUALIZAR_RESULTADO(5	, 12, 3, 3);
CALL ACTUALIZAR_RESULTADO(6	, 11, 1, 4);
CALL ACTUALIZAR_RESULTADO(7	, 10, 3, 3);
CALL ACTUALIZAR_RESULTADO(8	, 9 , 0, 4);

 
-- JORNADA 38
INSERT INTO PARTIDOS VALUES(1	, 19, NULL, NULL,   DEFAULT, 38, NULL);
INSERT INTO PARTIDOS VALUES(20	, 18, NULL, NULL,   DEFAULT, 38, NULL);
INSERT INTO PARTIDOS VALUES(2	, 17, NULL, NULL,   DEFAULT, 38, NULL);
INSERT INTO PARTIDOS VALUES(3	, 16, NULL, NULL,   DEFAULT, 38, NULL);
INSERT INTO PARTIDOS VALUES(4	, 15, NULL, NULL,   DEFAULT, 38, NULL);
INSERT INTO PARTIDOS VALUES(5	, 14, NULL, NULL,   DEFAULT, 38, NULL);
INSERT INTO PARTIDOS VALUES(6	, 13, NULL, NULL,   DEFAULT, 38, NULL);
INSERT INTO PARTIDOS VALUES(7	, 12, NULL, NULL,   DEFAULT, 38, NULL);
INSERT INTO PARTIDOS VALUES(8	, 11, NULL, NULL,   DEFAULT, 38, NULL);
INSERT INTO PARTIDOS VALUES(9	, 10, NULL, NULL,   DEFAULT, 38, NULL);
CALL ACTUALIZAR_RESULTADO(1	, 19, 4, 1);
CALL ACTUALIZAR_RESULTADO(20, 18, 2, 1);
CALL ACTUALIZAR_RESULTADO(2	, 17, 2, 2);
CALL ACTUALIZAR_RESULTADO(3	, 16, 3, 1);
CALL ACTUALIZAR_RESULTADO(4	, 15, 4, 1);
CALL ACTUALIZAR_RESULTADO(5	, 14, 1, 4);
CALL ACTUALIZAR_RESULTADO(6	, 13, 0, 4);
CALL ACTUALIZAR_RESULTADO(7	, 12, 0, 3);
CALL ACTUALIZAR_RESULTADO(8	, 11, 4, 4);
CALL ACTUALIZAR_RESULTADO(9	, 10, 1, 3);