-- --------------------------------- PRIMEROS PASOS-------------------------
DROP DATABASE IF EXISTS EXPORTACION;
CREATE DATABASE EXPORTACION;
USE EXPORTACION;


-- ---------------------------------------CREACION DE LA PRIMERA TABLA-------------------------------
DROP TABLE IF EXISTS PAIS;
CREATE TABLE PAIS (
ID_PAIS INT AUTO_INCREMENT,
NOMBRE CHAR(50),
PRIMARY KEY (ID_PAIS)
);


-- ----------------------------------------CREACION DE LA SEGUNDA TABLA---------------------------------
DROP TABLE IF EXISTS CLIENTE;
CREATE TABLE CLIENTE (
	ID_CLIENTE INT AUTO_INCREMENT,
	NOMBRE CHAR(50),
	ID_PAIS INT,
	PRIMARY KEY (ID_CLIENTE),
	FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS)
);

-- -----------------------------------------CREACION DE LA SEGUNDA TABLA------------------------------------------
DROP TABLE IF EXISTS PRODUCTO;
CREATE TABLE PRODUCTO (
	ID_PRODUCTO INT AUTO_INCREMENT,
    NOMBRE CHAR(50),
    DESCRIPCION VARCHAR(300),
    PRECIO FLOAT,
    PRIMARY KEY (ID_PRODUCTO)
);


-- ------------------------------------CREACION DE LA TERCERA TABLA--------------------------------------------
DROP TABLE IF EXISTS VENTA;
CREATE TABLE VENTA (
ID_VENTA INT,
ID_CLIENTE INT,
ID_PRODUCTO INT,
CANTIDAD INT,
TOTAL FLOAT,
PRIMARY KEY (ID_VENTA),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);


-- ------------------------------------------------INSERCCION DE LOS DATOS--------------------------------------------------
INSERT INTO PAIS VALUES (DEFAULT, 'Alemania');
INSERT INTO PAIS VALUES (DEFAULT, 'Bélgica');
INSERT INTO PAIS VALUES (DEFAULT, 'Croacia');
INSERT INTO PAIS VALUES (DEFAULT, 'Dinamarca');
INSERT INTO PAIS VALUES (DEFAULT, 'España');
INSERT INTO PAIS VALUES (DEFAULT, 'Francia');
INSERT INTO PAIS VALUES (DEFAULT, 'Irlanda');
INSERT INTO PAIS VALUES (DEFAULT, 'Letonia');
INSERT INTO PAIS VALUES (DEFAULT, 'Luxemburgo');
INSERT INTO PAIS VALUES (DEFAULT, 'Países Bajos');
INSERT INTO PAIS VALUES (DEFAULT, 'Suecia');
INSERT INTO PAIS VALUES (DEFAULT, 'Bulgaria');
INSERT INTO PAIS VALUES (DEFAULT, 'Eslovaquia');
INSERT INTO PAIS VALUES (DEFAULT, 'Estonia');
INSERT INTO PAIS VALUES (DEFAULT, 'Grecia');
INSERT INTO PAIS VALUES (DEFAULT, 'Malta');
INSERT INTO PAIS VALUES (DEFAULT, 'Polonia');
INSERT INTO PAIS VALUES (DEFAULT, 'República Checa');
INSERT INTO PAIS VALUES (DEFAULT, 'Austria');
INSERT INTO PAIS VALUES (DEFAULT, 'Chipre');
INSERT INTO PAIS VALUES (DEFAULT, 'Eslovenia');
INSERT INTO PAIS VALUES (DEFAULT, 'Finlandia');
INSERT INTO PAIS VALUES (DEFAULT, 'Hungría');
INSERT INTO PAIS VALUES (DEFAULT, 'Italia');
INSERT INTO PAIS VALUES (DEFAULT, 'Lituania');
INSERT INTO PAIS VALUES (DEFAULT, 'Portugal');
INSERT INTO PAIS VALUES (DEFAULT, 'Rumanía');

-- ------------------------PRIMEROS EJERCICIOS------------------------------------------------------
select * FROM PAIS;

SELECT *
FROM PAIS 
WHERE NOMBRE LIKE 'A%';

SELECT *
FROM PAIS 
WHERE NOMBRE LIKE '______'; 