DROP DATABASE IF EXISTS SUPERMERCADO_1;
CREATE DATABASE SUPERMERCADO_1;
USE SUPERMERCADO_1;

CREATE TABLE PRODUCTO (
	ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE CHAR(50),
    DESCRIPCION CHAR(200),
    PRECIO FLOAT,
    STOCK INT
    );
        
CREATE TABLE VENTA (
	ID_VENTA INT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUCTO INT,
    CANTIDAD INT,
    PRECIO FLOAT,
    TOTAL FLOAT,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
    );
    
CREATE TABLE EMPLEADO (
	ID_EMPLEADO INT PRIMARY KEY AUTO_INCREMENT,
	NOMBRE CHAR(50),
	APELLIDOS CHAR(200),
    USUARIO CHAR(50)
	);

CREATE TABLE ASIGNACION (
	ID_EMPLEADO INT, 
    ID_VENTA INT, 
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO),
    FOREIGN KEY (ID_VENTA) REFERENCES VENTA (ID_VENTA)
    );
    
    INSERT INTO PRODUCTO VALUES (DEFAULT, 'Baguette', 'Baguette 80% trigo 20% centeno', 1.00, 100);
    INSERT INTO PRODUCTO VALUES (DEFAULT, 'Coca-cola 2', 'Botella de Coca-cola de 2L', 1.50, 1000);
    INSERT INTO PRODUCTO VALUES (DEFAULT, 'Cheese Burger', 'Comida basura', 3.00, 2000);
    INSERT INTO EMPLEADO VALUES (DEFAULT, 'Ángeles', 'De Charlie','Cajero1');
    INSERT INTO EMPLEADO VALUES (DEFAULT, 'Pepito', 'Grillo','Cajero2');
    INSERT INTO EMPLEADO VALUES (DEFAULT, 'Paco', 'Palotes','Cajero3');
