DROP DATABASE IF EXISTS VUELOS;
CREATE DATABASE VUELOS;
USE VUELOS;
-- -------- CREAMOS LA PRIMERA TABLA DE PAISES---------------------
DROP TABLE IF EXISTS PAISES;
CREATE TABLE PAISES (
	ID_PAIS INT UNSIGNED AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_PAIS)
);

INSERT INTO PAISES VALUES(DEFAULT, 'España');
INSERT INTO PAISES VALUES(DEFAULT, 'Francia');
INSERT INTO PAISES VALUES(DEFAULT, 'Reino Unido');
INSERT INTO PAISES VALUES(DEFAULT, 'Italia');


-- -------------------- CREAMOS LA SEGUNDA TABLA DE AEROPUERTO---------------------------
DROP TABLE IF EXISTS AEROPUERTOS;
CREATE TABLE AEROPUERTOS (
	ID_AEROPUERTO INT UNSIGNED AUTO_INCREMENT,
    ID_PAIS INT UNSIGNED,
    NOMBRE VARCHAR(50),
    PRIMARY KEY (ID_AEROPUERTO),
    FOREIGN KEY (ID_PAIS) REFERENCES PAISES(ID_PAIS)
    
);

INSERT INTO AEROPUERTOS VALUES(DEFAULT, 1,'Oviedo');
INSERT INTO AEROPUERTOS VALUES(DEFAULT, 1,'Madrid');
INSERT INTO AEROPUERTOS VALUES(DEFAULT, 2,'París');
INSERT INTO AEROPUERTOS VALUES(DEFAULT, 3,'Londres');
INSERT INTO AEROPUERTOS VALUES(DEFAULT, 1,'Barcelona');
INSERT INTO AEROPUERTOS VALUES(DEFAULT, 4,'Milán');


-- ----------------------------CREAMOS LA TERCERA TABLA DE LOS VIAJES----------------------------
DROP TABLE IF EXISTS VIAJES;
CREATE TABLE VIAJES (
	ID_VUELO INT UNSIGNED AUTO_INCREMENT,
    ID_ORIGEN INT UNSIGNED,
    ID_DESTINO INT UNSIGNED,
    DURACION TIME,
    FECHA_HORA DATETIME,
    PRIMARY KEY (ID_VUELO),
    FOREIGN KEY (ID_ORIGEN) REFERENCES AEROPUERTOS(ID_AEROPUERTO),
    FOREIGN KEY (ID_DESTINO) REFERENCES AEROPUERTOS(ID_AEROPUERTO)
);



INSERT INTO VIAJES VALUES(DEFAULT, 1, 2, NULL, NULL), (DEFAULT, 1, 3, NULL, NULL),(DEFAULT, 1, 4, NULL, NULL),
                         (DEFAULT, 1, 5, NULL, NULL), (DEFAULT, 1, 6, NULL, NULL),(DEFAULT, 2, 3, NULL, NULL),
						 (DEFAULT, 2, 4, NULL, NULL), (DEFAULT, 2, 5, NULL, NULL),(DEFAULT, 2, 6, NULL, NULL),
                         (DEFAULT, 2, 1, NULL, NULL), (DEFAULT, 3, 4, NULL, NULL),(DEFAULT, 3, 5, NULL, NULL),
						 (DEFAULT, 3, 6, NULL, NULL), (DEFAULT, 3, 1, NULL, NULL),(DEFAULT, 3, 2, NULL, NULL),
                         (DEFAULT, 4, 5, NULL, NULL), (DEFAULT, 4, 6, NULL, NULL),(DEFAULT, 4, 1, NULL, NULL),
                         (DEFAULT, 4, 2, NULL, NULL), (DEFAULT, 4, 3, NULL, NULL),(DEFAULT, 5, 6, NULL, NULL),
                         (DEFAULT, 5, 1, NULL, NULL), (DEFAULT, 5, 2, NULL, NULL),(DEFAULT, 5, 3, NULL, NULL),
                         (DEFAULT, 5, 4, NULL, NULL), (DEFAULT, 6, 1, NULL, NULL),(DEFAULT, 6, 2, NULL, NULL),
                         (DEFAULT, 6, 3, NULL, NULL), (DEFAULT, 6, 4, NULL, NULL),(DEFAULT, 6, 5, NULL, NULL);
                             
                       
    
    
  
    
    



    