DROP TABLE IF EXISTS TIPO_VUELO;
CREATE TABLE TIPO_VUELO(
ID_TIPO CHAR(1),
TIPO_VUELO CHAR(20),
PRIMARY KEY (ID_TIPO),
CONSTRAINT CHK_VALUE CHECK(ID_TIPO IN ('V', 'F'))
);

INSERT INTO TIPO_VUELO VALUES('V', 'Directo'),('F','Con escala');

-- -----------------------------Empezamos a desnormalizacion ------------------------

ALTER TABLE VIAJES
ADD ID_TIPO_VUELO CHAR(1)
CHECK(ID_TIPO_VUELO IN ('V', 'F'))
AFTER TIPO_VUELO;

UPDATE VIAJES
SET ID_TIPO_VUELO = 'V'
WHERE TIPO_VUELO = 'Directo';

UPDATE VIAJES
SET ID_TIPO_VUELO = 'F'
WHERE TIPO_VUELO = 'Con escala';

ALTER TABLE VIAJES
DROP TIPO_VUELO;

-- ---------------------------------- Ahora cogemos los trayectos----------------------------

DROP TABLE IF EXISTS TRAYECTO;
CREATE TABLE TRAYECTO (
	ID_TRAYECTO INT AUTO_INCREMENT,
    ID_ORIGEN INT UNSIGNED,
    ID_DESTINO INT UNSIGNED,
    PRIMARY KEY (ID_TRAYECTO),
    FOREIGN KEY (ID_ORIGEN) REFERENCES AEROPUERTOS(ID_AEROPUERTO),
    FOREIGN KEY (ID_DESTINO) REFERENCES AEROPUERTOS(ID_AEROPUERTO)
);

INSERT INTO TRAYECTO VALUES (DEFAULT, 1, 2);
INSERT INTO TRAYECTO VALUES (DEFAULT, 1, 3);
INSERT INTO TRAYECTO VALUES (DEFAULT, 1, 4);
INSERT INTO TRAYECTO VALUES (DEFAULT, 1, 5);
INSERT INTO TRAYECTO VALUES (DEFAULT, 1, 6);
INSERT INTO TRAYECTO VALUES (DEFAULT, 2, 1);
INSERT INTO TRAYECTO VALUES (DEFAULT, 2, 3);
INSERT INTO TRAYECTO VALUES (DEFAULT, 2, 4);
INSERT INTO TRAYECTO VALUES (DEFAULT, 2, 5);
INSERT INTO TRAYECTO VALUES (DEFAULT, 2, 6);
INSERT INTO TRAYECTO VALUES (DEFAULT, 3, 1);
INSERT INTO TRAYECTO VALUES (DEFAULT, 3, 2);
INSERT INTO TRAYECTO VALUES (DEFAULT, 3, 4);
INSERT INTO TRAYECTO VALUES (DEFAULT, 3, 5);
INSERT INTO TRAYECTO VALUES (DEFAULT, 3, 6);
INSERT INTO TRAYECTO VALUES (DEFAULT, 4, 1);
INSERT INTO TRAYECTO VALUES (DEFAULT, 4, 2);
INSERT INTO TRAYECTO VALUES (DEFAULT, 4, 3);
INSERT INTO TRAYECTO VALUES (DEFAULT, 4, 5);
INSERT INTO TRAYECTO VALUES (DEFAULT, 4, 6);
INSERT INTO TRAYECTO VALUES (DEFAULT, 5, 1);
INSERT INTO TRAYECTO VALUES (DEFAULT, 5, 2);
INSERT INTO TRAYECTO VALUES (DEFAULT, 5, 3);
INSERT INTO TRAYECTO VALUES (DEFAULT, 5, 4);
INSERT INTO TRAYECTO VALUES (DEFAULT, 5, 6);
INSERT INTO TRAYECTO VALUES (DEFAULT, 6, 1);
INSERT INTO TRAYECTO VALUES (DEFAULT, 6, 2);
INSERT INTO TRAYECTO VALUES (DEFAULT, 6, 3);
INSERT INTO TRAYECTO VALUES (DEFAULT, 6, 4);
INSERT INTO TRAYECTO VALUES (DEFAULT, 6, 5);

-- -------------------------------------Ahora cogemos la de compania ------------------------------

DROP TABLE IF EXISTS COMPANIA;
CREATE TABLE COMPANIA (
	ID_COMPANIA INT AUTO_INCREMENT,
    NOMBRE VARCHAR(40),
    PRIMARY KEY (ID_COMPANIA)
);

INSERT INTO COMPANIA VALUES(DEFAULT, 'Avianca');
INSERT INTO COMPANIA VALUES(DEFAULT, 'EasyJet');
INSERT INTO COMPANIA VALUES(DEFAULT, 'Air France');
INSERT INTO COMPANIA VALUES(DEFAULT, 'Air Italia');


-- -------------------------------------Ahora cogemos la de detalles_vuelo------------------------------
DROP TABLE IF EXISTS DETALLES_VUELO;
CREATE TABLE DETALLES_VUELO (
	ID_DETALLES_VUELO INT AUTO_INCREMENT,
    ID_TRAYECTO INT,
    ID_COMPANIA INT,
    ID_TIPO CHAR(1),
    DURACION TIME,
    FECHA DATE,
    HORA TIME,
    PRIMARY KEY (ID_DETALLES_VUELO),
    FOREIGN KEY (ID_TRAYECTO) REFERENCES TRAYECTO(ID_TRAYECTO),
    FOREIGN KEY (ID_COMPANIA) REFERENCES COMPANIA(ID_COMPANIA),
    FOREIGN KEY (ID_TIPO) REFERENCES TIPO_VUELO(ID_TIPO),
    CHECK (ID_TIPO IN ('V', 'F'))
);

-- -----------------------------  hORARIOS DE PARIS A MILAN  ----------------------------------------------------------------------

SELECT A_ORIGEN AS 'AEROPUERTO ORIGEN', A_DESTINO AS 'AEROPUERTO DESTINO',DURACION,FECHA,HORA
FROM VIAJES
WHERE A_ORIGEN= 'PARIS' AND A_DESTINO = 'Milan';


SELECT ORIGEN.NOMBRE,
       DESTINO.NOMBRE,
       DETALLES_VUELO.DURACION,
       DETALLES_VUELO.FECHA,
       DETALLES_VUELO.HORA
       FROM DETALLES_VUELO
       INNER JOIN TRAYECTO ON DETALLES_VUELO.ID_TRAYECTO = TRAYECTO.ID_TRAYECTO
       INNER JOIN AEROPUERTOS ORIGEN ON ORIGEN.ID_AEROPUERTO = TRAYECTO.ID_ORIGEN
       INNER JOIN AEROPUERTOS DESTINO ON DESTINO.ID_AEROPUERTO = TRAYECTO.ID_DESTINO
       WHERE ORIGEN.NOMBRE = 'Paris' AND DESTINO.NOMBRE = 'Milan';
       
 -- ----------------------------- cuantos vuelos opera Air Italia el dia 10/08---------------
 
 select count(compania) as 'Numero de vuelos'
 from viajes
 where fecha = 20230810 and compania = 'Air Italia';
 
 
 select compania.nombre, detalles_vuelo.fecha
 from compania inner join detalles_vuelo on compania.id_compania = detalles_vuelo.ID_COMPANIA
 where compania.nombre = 'Air Italia' and detalles_vuelo.fecha = 20230810;
   
  -- ----------------------------- SABER CUANTOS VUELOS DIRECTO TIENE EASYJET, NOMBRE ORIGEN Y DESTINO------------
  
  SELECT VIAJES.COMPANIA,VIAJES.A_ORIGEN, VIAJES.A_DESTINO,  TIPO_VUELO.TIPO_VUELO
  FROM VIAJES INNER JOIN TIPO_VUELO ON VIAJES.ID_TIPO_VUELO = TIPO_VUELO.ID_TIPO
  WHERE VIAJES.COMPANIA = 'Easyjet' AND TIPO_VUELO.TIPO_VUELO = 'DIRECTO';
  
  
  SELECT COMPANIA.NOMBRE,
	   A_ORIGEN.NOMBRE,
       A_DESTINO.NOMBRE,
       TIPO_VUELO.TIPO_VUELO
       FROM TRAYECTO 
		INNER JOIN AEROPUERTOS A_ORIGEN ON A_ORIGEN.ID_AEROPUERTO = TRAYECTO.ID_ORIGEN
        INNER JOIN AEROPUERTOS A_DESTINO ON A_DESTINO.ID_AEROPUERTO = TRAYECTO.ID_DESTINO
			INNER JOIN DETALLES_VUELO ON DETALLES_VUELO.ID_TRAYECTO = TRAYECTO.ID_TRAYECTO
            INNER JOIN TIPO_VUELO ON TIPO_VUELO.ID_TIPO = DETALLES_VUELO.ID_TIPO
            INNER JOIN COMPANIA ON COMPANIA.ID_COMPANIA = DETALLES_VUELO.ID_COMPANIA
				WHERE COMPANIA.NOMBRE = 'EasyJet' AND TIPO_VUELO.TIPO_VUELO = 'Directo';
                
                
  -- ------------------------------------------¿En que fecha hay un vuelo directo de Paris a Madrid?
  
  SELECT VIAJES.A_ORIGEN, VIAJES.A_DESTINO, VIAJES.FECHA, TIPO_VUELO.TIPO_VUELO
  FROM VIAJES
  INNER JOIN TIPO_VUELO ON VIAJES.ID_TIPO_VUELO = TIPO_VUELO.ID_TIPO
  WHERE A_ORIGEN = 'PARIS' AND A_DESTINO = 'mADRID' AND TIPO_VUELO.TIPO_VUELO = 'DIRECTO';
  
  SELECT  A_ORIGEN.NOMBRE,
         A_DESTINO.NOMBRE,
         DETALLES_VUELO.FECHA,
         TIPO_VUELO.TIPO_VUELO
         FROM TRAYECTO 
         INNER JOIN AEROPUERTOS A_ORIGEN ON A_ORIGEN.ID_AEROPUERTO = TRAYECTO.ID_ORIGEN
        INNER JOIN AEROPUERTOS A_DESTINO ON A_DESTINO.ID_AEROPUERTO = TRAYECTO.ID_DESTINO
        INNER JOIN DETALLES_VUELO ON DETALLES_VUELO.ID_TRAYECTO = TRAYECTO.ID_TRAYECTO
         INNER JOIN TIPO_VUELO ON TIPO_VUELO.ID_TIPO = DETALLES_VUELO.ID_TIPO
        WHERE A_ORIGEN.NOMBRE = 'PARIS' AND A_DESTINO.NOMBRE = 'mADRID' AND TIPO_VUELO.TIPO_VUELO = 'DIRECTO' ;
        
  -- ---------------------------------------------¿SACAR LOS HORARIOS DE LOS VUELOS  DE MADRID A OVIEDO ------------------------
  SELECT  VIAJES.A_ORIGEN, VIAJES.A_DESTINO,VIAJES.HORA ,VIAJES.FECHA
  FROM VIAJES
  WHERE A_ORIGEN = 'MADRID' AND A_DESTINO = 'OVIEDO';
  
  
  SELECT  ORIGEN.NOMBRE,
         DESTINO.NOMBRE,
         DETALLES_VUELO.FECHA,
         DETALLES_VUELO.HORA
         FROM TRAYECTO 
         INNER JOIN AEROPUERTOS ORIGEN ON ORIGEN.ID_AEROPUERTO = TRAYECTO.ID_ORIGEN
        INNER JOIN AEROPUERTOS DESTINO ON DESTINO.ID_AEROPUERTO = TRAYECTO.ID_DESTINO
        INNER JOIN DETALLES_VUELO ON DETALLES_VUELO.ID_TRAYECTO = TRAYECTO.ID_TRAYECTO        
        WHERE ORIGEN.NOMBRE = 'MADRID' AND DESTINO.NOMBRE = 'OVIEDO'  ;
        
   -- --------------------------------------------CONSULTA A LAS TABLAS NORMALIZADAS QUE SEAN EQUIVALENTES A SELECT * DE VIAJES--------------     
         
         SELECT DETALLES_VUELO.ID_DETALLES_VUELO AS 'CODIGO',
                ORIGEN.NOMBRE AS 'CUIDAD ORIGEN',
                O_PAISES.NOMBRE AS 'PAIS ORIGEN',
                DESTINO.NOMBRE AS 'CIUDAD DESTINO',
                D_PAISES.NOMBRE AS 'PAIS DESTINO',
                COMPANIA.NOMBRE AS 'COMPAÑIA',
                TIPO_VUELO.TIPO_VUELO AS 'TRAYECTO',
                DETALLES_VUELO.DURACION AS 'DURACION',
                DETALLES_VUELO.HORA AS 'HORA',
                DETALLES_VUELO.FECHA AS 'FECHA'
           FROM DETALLES_VUELO
				INNER JOIN TRAYECTO ON DETALLES_VUELO.ID_TRAYECTO = TRAYECTO.ID_TRAYECTO
                INNER JOIN AEROPUERTOS ORIGEN ON ORIGEN.ID_AEROPUERTO = TRAYECTO.ID_ORIGEN
                INNER JOIN AEROPUERTOS DESTINO ON DESTINO.ID_AEROPUERTO = TRAYECTO.ID_DESTINO
                INNER JOIN PAISES O_PAISES ON O_PAISES.ID_PAIS = ORIGEN.ID_PAIS
                INNER JOIN PAISES D_PAISES ON D_PAISES.ID_PAIS = DESTINO.ID_PAIS
                INNER JOIN COMPANIA ON DETALLES_VUELO.ID_COMPANIA = COMPANIA.ID_COMPANIA
                INNER JOIN TIPO_VUELO ON TIPO_VUELO.ID_TIPO = DETALLES_VUELO.ID_TIPO
                ORDER BY ID_DETALLES_VUELO;
                
     -- ----------------------------------------------------
     
     SELECT ID_VUELO, A_ORIGEN,A_DESTINO,TIPO_VUELO.TIPO_VUELO, FECHA, HORA
     FROM VIAJES
     INNER JOIN TIPO_VUELO ON TIPO_VUELO.ID_TIPO = VIAJES.ID_TIPO_VUELO
     WHERE A_ORIGEN = 'MILAN' AND FECHA = '20230813';
     
     
     SELECT DETALLES_VUELO.ID_DETALLES_VUELO AS 'CODIGO VUELO',
            ORIGEN.NOMBRE AS 'CUIDAD ORIGEN',
            DESTINO.NOMBRE AS 'CUIDAD DESTINO',
            TIPO_VUELO.TIPO_VUELO 'TIPO VUELO',
            DETALLES_VUELO.FECHA,
            DETALLES_VUELO.HORA
      FROM DETALLES_VUELO
           INNER JOIN TRAYECTO ON TRAYECTO.ID_TRAYECTO = DETALLES_VUELO.ID_TRAYECTO
           INNER JOIN AEROPUERTOS ORIGEN ON ORIGEN.ID_AEROPUERTO = TRAYECTO.ID_ORIGEN
           INNER JOIN AEROPUERTOS DESTINO ON DESTINO.ID_AEROPUERTO = TRAYECTO.ID_DESTINO
           INNER JOIN TIPO_VUELO ON TIPO_VUELO.ID_TIPO = DETALLES_VUELO.ID_TIPO
           WHERE ORIGEN.NOMBRE = 'MILAN' AND DETALLES_VUELO.FECHA = '20230813';
           
     -- -------------------------------- ORIGEN, PAIS, DESTINO. PAIS. FECHA U HORA QUE OPERA AIR ITALIA
     
     
     SELECT A_ORIGEN, PAIS_ORIGEN, A_DESTINO, PAIS_DESTINO, FECHA, HORA, COMPANIA
     FROM VIAJES
     WHERE COMPANIA = 'AIR ITALIA'
     ORDER BY FECHA ASC, HORA ASC;
     
     
      SELECT ORIGEN.NOMBRE AS 'CUIDAD DE ORIGEN',
             O_PAISES.NOMBRE AS 'PAIS DE ORIGEN',
             DESTINO.NOMBRE AS 'CIUDAD DE DESTINO',
             D_PAISES.NOMBRE AS 'PAIS DE DESTINO',
             DETALLES_VUELO.FECHA,
             DETALLES_VUELO.HORA,
            COMPANIA.NOMBRE AS 'COMPAÑIA'
      FROM  DETALLES_VUELO
       INNER JOIN TRAYECTO ON TRAYECTO.ID_TRAYECTO = DETALLES_VUELO.ID_TRAYECTO
      INNER JOIN AEROPUERTOS ORIGEN ON ORIGEN.ID_AEROPUERTO = TRAYECTO.ID_ORIGEN
      INNER JOIN AEROPUERTOS DESTINO ON DESTINO.ID_AEROPUERTO = TRAYECTO.ID_DESTINO
      INNER JOIN PAISES O_PAISES ON O_PAISES.ID_PAIS = ORIGEN.ID_PAIS
      INNER JOIN PAISES D_PAISES ON D_PAISES.ID_PAIS = DESTINO.ID_PAIS
      INNER JOIN COMPANIA ON DETALLES_VUELO.ID_COMPANIA = COMPANIA.ID_COMPANIA
       WHERE COMPANIA.NOMBRE = 'AIR ITALIA'
       ORDER BY FECHA ASC, HORA ASC;
           
                