DROP DATABASE IF EXISTS VIOGEN;
CREATE DATABASE VIOGEN;
USE VIOGEN;


DROP TABLE IF EXISTS RIESGO;
CREATE TABLE RIESGO (
	COD_RIESGO CHAR(1),
    RIESGO VARCHAR(20),
	CONSTRAINT PK_RIESGO PRIMARY KEY (COD_RIESGO)
);

DROP TABLE IF EXISTS USUARIAS;
CREATE TABLE USUARIAS (
	COD_USUARIA INT AUTO_INCREMENT,
    DNI CHAR(9),
    NIE CHAR(9),   
    NOMBRE VARCHAR(100),
    APELLIDO1 VARCHAR(100),
    APELLIDO2 VARCHAR(100),
    NACIONALIDAD VARCHAR(40),
    TELEFONO VARCHAR(12),
    DIRECCION VARCHAR(200),
    CP CHAR(5),
    COD_RIESGO CHAR(1),
    INFO_RAI CHAR(1) DEFAULT '',
    INFO_PAGO_UNICO CHAR(1) DEFAULT '',
    INFO_VIPASA CHAR(1) DEFAULT '',
    INFO_AYUDA_EMERGENCIA CHAR(1) DEFAULT '',
    CONSTRAINT PK_USUARIAS PRIMARY KEY (COD_USUARIA),
    CONSTRAINT UK_DNI_NIE UNIQUE KEY (DNI,NIE),
    CONSTRAINT FK_USUARIAS_RIESGO FOREIGN KEY (COD_RIESGO) REFERENCES RIESGO(COD_RIESGO),
    CONSTRAINT CK_DNI CHECK((substring(DNI, 1, 7) REGEXP '[0-9]' AND SUBSTRING(DNI, 9, 1) REGEXP '[A-Z]') OR DNI =''),
    CONSTRAINT CK_NIE CHECK((substring(NIE, 1, 1) REGEXP '[A-Z]' AND SUBSTRING(DNI, 2, 7) REGEXP '[0-9]' AND SUBSTRING(NIE, 9, 1) REGEXP '[A-Z]')OR NIE =''),
	CONSTRAINT CK_INFO_RAI CHECK(INFO_RAI IN ('', 'X')),
    CONSTRAINT CK_INFO_PAGO_UNICO CHECK(INFO_PAGO_UNICO IN ('', 'X')),
    CONSTRAINT CK_INFO_VIPASA CHECK(INFO_VIPASA IN ('', 'X')),
    CONSTRAINT CK_INFO_AYUDA_EMERGENCIA CHECK(INFO_AYUDA_EMERGENCIA IN ('', 'X'))
    
);

DROP TABLE IF EXISTS AGRESORES;
CREATE TABLE AGRESORES(
       COD_AGRESOR INT AUTO_INCREMENT,
       DNI CHAR(9),
       NIE CHAR(9),
       NOMBRE VARCHAR(100),
       APELLIDOS1 VARCHAR(100),
       APELLIDO2 VARCHAR(100),
       CONSTRAINT PK_AGRESORES PRIMARY KEY (COD_AGRESOR),
       CONSTRAINT CK_DNI_AG CHECK(substring(DNI, 1, 7) REGEXP '[0-9]' AND SUBSTRING(DNI, 9, 1) REGEXP '[A-Z]'),
       CONSTRAINT CK_NIE_AG CHECK((substring(NIE, 1, 1) REGEXP '[A-Z]' AND SUBSTRING(DNI, 2, 7) REGEXP '[0-9]' AND SUBSTRING(NIE, 9, 1) REGEXP '[A-Z]')OR NIE ='')
);

DROP TABLE IF EXISTS VINCULOS;
CREATE TABLE VINCULOS(
         COD_USUARIA INT,
         COD_AGRESOR INT,
         CONSTRAINT PK_VINCULOS PRIMARY KEY (COD_USUARIA, COD_AGRESOR),
         CONSTRAINT FK_VINCULOS_USUARIAS FOREIGN KEY (COD_USUARIA) REFERENCES USUARIAS(COD_USUARIA),
         CONSTRAINT FK_VINCULOS_AGRESORES FOREIGN KEY (COD_AGRESOR) REFERENCES AGRESORES(COD_AGRESOR)
         
);



DROP TABLE IF EXISTS HISTORIAL;
CREATE TABLE HISTORIAL (
	COD_USUARIA INT,
    COD_RIESGO CHAR(1),
    FECHA_CAMBIO DATE DEFAULT (CURRENT_DATE),
	CONSTRAINT PK_HISTORIAL PRIMARY KEY (COD_USUARIA, COD_RIESGO, FECHA_CAMBIO),
    CONSTRAINT FK_HISTORIAL_USUARIAS FOREIGN KEY (COD_USUARIA) REFERENCES USUARIAS(COD_USUARIA),
    CONSTRAINT FK_HISTORIAL_RIESGO FOREIGN KEY (COD_RIESGO) REFERENCES RIESGO(COD_RIESGO)
);

DROP TABLE IF EXISTS ORDEN_PROTEC;
CREATE TABLE ORDEN_PROTEC (
	COD_ORDEN INT AUTO_INCREMENT,
    COD_USUARIA INT,
    COD_AGRESOR INT,
    EXPEDIENTE CHAR(20),
    FECHA_INICIO DATE DEFAULT (CURRENT_DATE),
    FECHA_FIN DATE,
    CONSTRAINT PK_ORDEN_PROTEC PRIMARY KEY (COD_ORDEN),
    CONSTRAINT FK_ORDEN_PROTEC_USUARIAS FOREIGN KEY (COD_USUARIA) REFERENCES USUARIAS(COD_USUARIA),
    CONSTRAINT FK_ORDEN_PROTEC_AGRESORES FOREIGN KEY (COD_AGRESOR) REFERENCES AGRESORES(COD_AGRESOR)
);

DROP TABLE IF EXISTS JURISDICCION;
CREATE TABLE JURISDICCION (
	COD_JURISDICCION CHAR(1),
    JURISDICCION CHAR(20),
    CONSTRAINT PK_JURISDICCION PRIMARY KEY (COD_JURISDICCION)
);

DROP TABLE IF EXISTS MEDIDAS;
CREATE TABLE MEDIDAS (
	COD_MEDIDA INT AUTO_INCREMENT,
    COD_ORDEN INT,
    COD_JURISDICCION CHAR(1),
    CONTENIDO VARCHAR(3000),
    FECHA_INICIO DATE DEFAULT (CURRENT_DATE),
    FECHA_FIN DATE,
    CONSTRAINT PK_MEDIDAS PRIMARY KEY (COD_MEDIDA),
    CONSTRAINT FK_MEDIDAS_ORDEN_PROTEC FOREIGN KEY (COD_ORDEN) REFERENCES ORDEN_PROTEC(COD_ORDEN),
    CONSTRAINT FK_MEDIDAS_JURISDICCION FOREIGN KEY (COD_JURISDICCION) REFERENCES JURISDICCION(COD_JURISDICCION)
);




INSERT INTO JURISDICCION VALUES ('C', 'Civil'), ('P', 'Penal');
INSERT INTO RIESGO VALUES ('E', 'Extremo'), ('A', 'Alto'),('M', 'Medio'),('B', 'Bajo'),('N', 'Nulo');



/*INSERT INTO USUARIAS VALUES(DEFAULT, '11111111B',  'Melba',       'Wulfinger',    'Limb',      '132456987', 'Cheban',              '32165', 'A', DEFAULT, DEFAULT, DEFAULT, DEFAULT);              
INSERT INTO USUARIAS VALUES(DEFAULT, '21111111B',  'Maryrose',    'Easson',       'Posten',    '132456987', 'Shuinan',             '32165', 'E', DEFAULT, DEFAULT, DEFAULT, DEFAULT);         
INSERT INTO USUARIAS VALUES(DEFAULT, '31111111B',  'Sophronia',   'Broadfield',   'Maylam',    '132456987', 'Montreuil',           '32165', 'M', DEFAULT, DEFAULT, DEFAULT, DEFAULT);           
INSERT INTO USUARIAS VALUES(DEFAULT, '41111111B',  'Cybill',      'Robertson',    'Ligerton',  '132456987', 'Tukums',              '32165', 'M', DEFAULT, DEFAULT, DEFAULT, DEFAULT);              
INSERT INTO USUARIAS VALUES(DEFAULT, '51111111B',  'Fredra',      'Greville',     'Roke',      '132456987', 'Rēzekne',             '32165', 'M', DEFAULT, DEFAULT, DEFAULT, DEFAULT);             
INSERT INTO USUARIAS VALUES(DEFAULT, '61111111B',  'Gusta',       'Dundendale',   'La Croce',  '132456987', 'Lintan Chengguanzhen','32165', 'M', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO USUARIAS VALUES(DEFAULT, '71111111B',  'Janie',       'Hollow',       'Trustram',  '132456987', 'Sātkania',            '32165', 'B', DEFAULT, DEFAULT, DEFAULT, DEFAULT);          
INSERT INTO USUARIAS VALUES(DEFAULT, '81111111B',  'Vyky',        'Jery',         'Lumm',      '132456987', 'Nice',                '32165', 'B', DEFAULT, DEFAULT, DEFAULT, DEFAULT);              
INSERT INTO USUARIAS VALUES(DEFAULT, '91111111B',  'Catharine'	, 'Waddilow',     'Eskriett',  '132456987', 'Talata Mafara',       '32165', 'B', DEFAULT, DEFAULT, DEFAULT, DEFAULT);     
INSERT INTO USUARIAS VALUES(DEFAULT, '10111111B',  'Ruthie' ,   'Canepe',       'Maulin',      '132456987', 'Casillas',            '32165', 'B', DEFAULT, DEFAULT, DEFAULT, DEFAULT);          
INSERT INTO USUARIAS VALUES(DEFAULT, '11111111B',  'Dolores' ,   'Griffiths',    'Morstatt',   '132456987', 'Fuwen',               '32165', 'B', DEFAULT, DEFAULT, DEFAULT, DEFAULT);             
INSERT INTO USUARIAS VALUES(DEFAULT, '12111111B',  'Nissie',    'Duncan',       'Butts',       '132456987', 'Öldziyt',             '32165', 'A', DEFAULT, DEFAULT, DEFAULT, DEFAULT);           
INSERT INTO USUARIAS VALUES(DEFAULT, '13111111B',  'Bennie',    'Mostyn',       'Shackleton',  '132456987', 'Robertsport',         '32165', 'A', DEFAULT, DEFAULT, DEFAULT, DEFAULT);               
INSERT INTO USUARIAS VALUES(DEFAULT, '14111111B',  'Max',    'Catterill',    'Aird',           '132456987', 'Luleå',               '32165', 'E', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO USUARIAS VALUES(DEFAULT, '15111111B',  'Clemmy',    'Cheales',      'Dyneley',     '132456987', 'Amnat Charoen',       '32165', 'E', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO USUARIAS VALUES(DEFAULT, '16111111B',  'Kiley',    'Kinghorne',    'Bummfrey',     '132456987', 'Zhangyelu',           '32165', 'E', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO USUARIAS VALUES(DEFAULT, '17111111B',  'Odella',    'Thebeaud'	,     'Comport',   '132456987', 'Kiarajangkung',       '32165', 'E', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO USUARIAS VALUES(DEFAULT, '18111111B',  'Blanca',    'Huygens',      'Kuhn',        '132456987', 'Oslo',                '32165', 'E', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO USUARIAS VALUES(DEFAULT, '19111111B',  'Coretta',    'Cooling',      'Henriquet',  '132456987', 'Yaita',               '32165', 'N', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO USUARIAS VALUES(DEFAULT, '20111111B',  'Myrtie',    'Blakeslee',    'Halbard',     '132456987', 'Baitu',               '32165', 'N', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO USUARIAS VALUES(DEFAULT, '21111111B',  'Adoree',    'Mowday',       'Crang',       '132456987', 'Baitu',               '32165', 'N', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO USUARIAS VALUES(DEFAULT, '22111111B',  'Arlette	',    'O Shea',       'Balam',     '132456987', 'Galutu',              '32165', 'N', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO USUARIAS VALUES(DEFAULT, '23111111B',  'Kristyn	',    'Jirousek',     'Kenewell',  '132456987', 'Jinshiqiao',          '32165', 'N', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO USUARIAS VALUES(DEFAULT, '24111111B',  'Ursulina',    'Geach',        'Rheubottom','132456987', 'Janakkala',           '32165', 'E', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO USUARIAS VALUES(DEFAULT, '25111111B',  'Kiersten',    'Wakely',       'Goodliffe', '132456987', 'Xike',                '32165', 'E', DEFAULT, DEFAULT, DEFAULT, DEFAULT);*/

